// Polish translations. Keys are the English source strings used in App.jsx.
export default {
  // navigation and shell
  "Watch": "Podgląd",
  "Configure": "Konfiguracja",
  "Prove": "Dowody",
  "Live": "Na żywo",
  "Tasks": "Zadania",
  "Audit log": "Dziennik audytu",
  "Controls": "Kontrole",
  "Policy file": "Plik polityki",
  "Attack signatures": "Sygnatury ataków",
  "Tools": "Narzędzia",
  "Run a scenario": "Scenariusze",
  "Test an input": "Sprawdź treść",
  "Budget": "Budżet",
  "Sections": "Sekcje",
  "Language": "Język",
  "Admin key": "Klucz administratora",
  "Current security posture": "Bieżący stan zabezpieczeń",
  "Gateway healthy": "Bramka działa",
  "Gateway degraded": "Bramka ma problem",
  "Connecting": "Łączenie",
  "Policy": "Polityka",
  "Profile": "Profil",
  "AI review on {model}": "Ocena AI: {model}",
  "Test mode: prompts go to OpenRouter (cloud)": "Tryb testowy: prompty idą do OpenRouter (chmura)",
  "AI review on the local scorer": "Ocena AI przez lokalny klasyfikator",
  "{n} attack signatures": "Sygnatur ataków: {n}",
  "AI review forced to “safe” (demo)": "Ocena AI wymuszona na „bezpieczne” (demo)",
  "Off: {list}": "Wyłączone: {list}",

  // decisions
  "Allowed": "Dozwolone",
  "Redacted": "Zredagowane",
  "Blocked": "Zablokowane",
  "allowed": "dozwolonych",
  "redacted": "zredagowanych",
  "blocked": "zablokowanych",
  "Redact": "Redaguj",
  "Block": "Blokuj",

  // live
  "Connecting to the gateway…": "Łączenie z bramką…",
  "No agent traffic yet. Run a scenario to see decisions here.": "Agenci jeszcze nic nie robili. Uruchom scenariusz, a decyzje pojawią się tutaj.",
  "decisions so far:": "decyzji do tej pory:",
  "Decisions as they happen": "Decyzje na bieżąco",
  "Streaming": "Na żywo",
  "tool ran": "narzędzie wykonane",
  "never reached the tool": "nie dotarło do narzędzia",
  "Waiting for the next request. Open “Run a scenario” in another tab and watch it arrive.": "Czekam na kolejne żądanie. Otwórz „Scenariusze” w innej karcie i obserwuj, jak spływają decyzje.",
  "What actually reached the tools": "Co naprawdę dotarło do narzędzi",
  "e-mails delivered by the mail server": "e-maili wysłanych przez serwer pocztowy",
  "External HTTP posts": "Wysyłki HTTP na zewnątrz",
  "Memos saved": "Zapisane notatki",
  "{n} calls": "wywołań: {n}",
  "Counted inside the tool service itself. A blocked request never increments these.": "Liczone wewnątrz usługi narzędzi. Zablokowane żądanie nigdy nie zwiększa tych liczników.",
  "The tool service is not responding.": "Usługa narzędzi nie odpowiada.",
  "Spend": "Wydatki",
  "Tokens spent": "Zużyte tokeny",
  "Held in reservations": "Zarezerwowane",
  "Estimated cost": "Szacowany koszt",
  "Active tasks": "Aktywne zadania",
  "Time added by checks": "Czas dodany przez kontrole",
  "milliseconds": "milisekundy",
  "Stage": "Etap",
  "median": "mediana",
  "Whole decision": "Cała decyzja",
  "Rules doing the most work": "Najczęściej działające reguły",
  "{used} of {limit} tokens used": "Zużyto {used} z {limit} tokenów",
  "{time}: {a} allowed, {r} redacted, {b} blocked": "{time}: dozwolone {a}, zredagowane {r}, zablokowane {b}",
  "Decisions per minute, last hour": "Decyzje na minutę, ostatnia godzina",

  // scenarios
  "Each scenario drives a scripted agent through the real gateway, database and tool service. Nothing is mocked except the agent's choices.": "Każdy scenariusz prowadzi zaprogramowanego agenta przez prawdziwą bramkę, bazę danych i usługę narzędzi. Symulowane są tylko decyzje samego agenta.",
  "Run": "Uruchom",
  "Running…": "Trwa…",
  "{name}: finished": "{name}: zakończono",
  "A normal day": "Zwykły dzień pracy",
  "The agent searches case law, reads the client's contract, asks the local model for risks and files a memo.": "Agent przeszukuje orzecznictwo, czyta umowę klienta, pyta lokalny model o ryzyka i zapisuje notatkę.",
  "Poisoned contract": "Zatruta umowa",
  "The contract hides an instruction to e-mail it to an outside address. The agent tries.": "W umowie ukryto polecenie wysłania jej na obcy adres. Agent próbuje to zrobić.",
  "The AI detector misses": "Detektor AI przeocza atak",
  "The semantic detector is forced to say “safe” and the recipient is one the mandate allows. Only data lineage is left to stop it.": "Detektor semantyczny ma wymuszone „bezpieczne”, a odbiorca jest dozwolony w mandacie. Zatrzymać wyciek może już tylko śledzenie pochodzenia danych.",
  "Wrong client's files": "Dokumenty innego klienta",
  "An agent working for client A reaches for client B's NDA, then tries a path trick.": "Agent pracujący dla klienta A sięga po NDA klienta B, a potem próbuje sztuczki ze ścieżką.",
  "Reused credentials": "Ponowne użycie przepustki",
  "The task ends, the agent keeps its lease and tries to use it again.": "Zadanie się kończy, agent zachowuje przepustkę i próbuje jej użyć ponownie.",
  "Tool changes after approval": "Narzędzie zmienione po zatwierdzeniu",
  "The MCP server silently rewrites a tool description to include an exfiltration instruction.": "Serwer MCP po cichu zmienia opis narzędzia i dopisuje polecenie wyniesienia danych.",
  "Model supply chain": "Łańcuch dostaw modeli",
  "Four models are registered: one clean, one with a pickle that imports os, one hit by CVE-2024-34359, one from a typosquatted host.": "Rejestrujemy cztery modele: czysty, z plikiem pickle importującym os, podatny na CVE-2024-34359 i pobrany z podrobionej domeny.",
  "Thirty agents, one budget": "Trzydziestu agentów, jeden budżet",
  "Thirty agents race for a 10,000-token pool at 1,000 tokens each.": "Trzydziestu agentów walczy o pulę 10 000 tokenów, po 1000 tokenów każdy.",
  "Decisions recorded by the gateway, in order": "Decyzje zapisane przez bramkę, w kolejności",
  "e-mails left the building.": "e-maili opuściło firmę.",
  "e-mail(s) reached the mail server.": "e-mail(e) dotarły do serwera pocztowego.",
  "tokens over budget.": "tokenów ponad budżet.",
  "{ran} agents ran, {stopped} were stopped before calling the model.": "Wykonało się {ran} agentów, {stopped} zatrzymano przed wywołaniem modelu.",
  "Rejected: {why}.": "Odrzucono: {why}.",
  "The tool ran.": "Narzędzie zostało wykonane.",
  "The tool was never called.": "Narzędzie nie zostało wywołane.",
  "Visible tools: {list}.": "Widoczne narzędzia: {list}.",
  "Also flagged: {list}.": "Oznaczono też: {list}.",
  "Rules that fired:": "Zadziałały reguły:",
  "The document was read, but its content was held back from the agent.": "Dokument odczytano, ale jego treść zatrzymano przed agentem.",
  "The document was read and handed over with the dangerous part removed.": "Dokument odczytano i przekazano bez niebezpiecznego fragmentu.",

  // scenario steps (from the backend)
  "search case law": "wyszukanie orzecznictwa",
  "read contract": "odczyt umowy",
  "summarise with local model": "streszczenie przez lokalny model",
  "save internal memo": "zapis notatki wewnętrznej",
  "read poisoned contract": "odczyt zatrutej umowy",
  "compromised agent tries to exfiltrate": "przejęty agent próbuje wynieść dane",
  "legit memo still works": "zwykła notatka nadal działa",
  "read poisoned contract (detector says SAFE)": "odczyt zatrutej umowy (detektor mówi „bezpieczne”)",
  "send contract to an ALLOWED external recipient": "wysyłka umowy do DOZWOLONEGO odbiorcy zewnętrznego",
  "read client B NDA": "odczyt NDA klienta B",
  "path traversal attempt": "próba obejścia ścieżką",
  "during task": "w trakcie zadania",
  "reuse lease after completion": "użycie przepustki po zakończeniu zadania",
  "tools/list (approved)": "tools/list (zatwierdzone)",
  "tools/list (after silent change)": "tools/list (po cichej zmianie)",
  "tools/call quarantined tool": "tools/call narzędzia w kwarantannie",
  "server reverted + admin re-approved": "serwer przywrócony i ponownie zatwierdzony",
  "safe model": "bezpieczny model",
  "pickle importing os.*": "pickle importujący os.*",
  "typosquat source": "podrobiona domena",

  // playground
  "Text to check": "Treść do sprawdzenia",
  "Where it comes from": "Skąd pochodzi",
  "Where it is going": "Dokąd trafia",
  "Most sensitive data the task has read": "Najbardziej poufne dane, które zadanie już przeczytało",
  "Check this input": "Sprawdź",
  "A dry run: the gateway decides, but no model or tool is called.": "Próba na sucho: bramka podejmuje decyzję, ale nie wywołuje modelu ani narzędzia.",
  "Checked. Nothing was executed.": "Sprawdzono. Nic nie zostało wykonane.",
  "A document or tool result the agent reads": "Dokument lub wynik narzędzia czytany przez agenta",
  "A message from the user": "Wiadomość od użytkownika",
  "Arguments the agent sends to a tool": "Argumenty wysyłane przez agenta do narzędzia",
  "The model's answer": "Odpowiedź modelu",
  "Nowhere, just inspect it": "Nigdzie, tylko sprawdź",
  "E-mail outside the firm": "E-mail poza firmę",
  "E-mail inside the firm": "E-mail wewnątrz firmy",
  "Post to an external URL": "Wysyłka na zewnętrzny adres URL",
  "Internal case notes": "Wewnętrzne notatki sprawy",
  "Case-law search query": "Zapytanie do bazy orzecznictwa",
  "Local model prompt": "Prompt do lokalnego modelu",
  "Nothing to stop": "Nie ma czego zatrzymywać",
  "decided in {ms} ms": "zdecydowała w {ms} ms",
  "What the agent would receive": "Co otrzymałby agent",
  "Write or paste anything, then check it. Try a PESEL number, a hidden instruction, or confidential data heading to an outside address.": "Wpisz lub wklej dowolną treść i sprawdź ją. Spróbuj numeru PESEL, ukrytego polecenia albo poufnych danych wysyłanych na zewnątrz.",
  "found {list}": "wykryto: {list}",
  "matched {list}": "dopasowano: {list}",
  "risk {risk} from {backend}": "ryzyko {risk} według: {backend}",
  "{level} data cannot go to {sink} (cleared for {clearance})": "dane {level} nie mogą trafić do {sink} (dopuszczone: {clearance})",

  // controls
  "Loading controls…": "Wczytywanie kontroli…",
  "Strictness": "Poziom rygoru",
  "Sets the defaults for every control below. A setting changed on a single control overrides it.": "Ustawia wartości domyślne dla wszystkich kontroli poniżej. Zmiana ustawienia pojedynczej kontroli ma pierwszeństwo.",
  "Switched to {p}": "Przełączono na: {p}",
  "{what}. Policy is now {v}.": "{what}. Aktualna polityka: {v}.",
  "on": "włączone",
  "off": "wyłączone",
  "Off. Requests are not checked for this.": "Wyłączone. Żądania nie są pod tym kątem sprawdzane.",
  "Task mandates": "Mandaty zadań",
  "Each task may only use its own tools, files and recipients, until it ends.": "Każde zadanie może używać tylko własnych narzędzi, plików i odbiorców, i tylko do swojego zakończenia.",
  "Data lineage": "Pochodzenie danych",
  "Once a task reads confidential data, it cannot send anything to a less trusted place.": "Gdy zadanie przeczyta poufne dane, nie może już niczego wysłać w mniej zaufane miejsce.",
  "Approved models only": "Tylko zatwierdzone modele",
  "Requests to models outside the list are refused.": "Żądania do modeli spoza listy są odrzucane.",
  "Personal data": "Dane osobowe",
  "PESEL, card numbers, IBANs, e-mail addresses and phone numbers.": "PESEL, numery kart, IBAN, adresy e-mail i numery telefonów.",
  "Credentials and keys": "Hasła i klucze",
  "Cloud keys, private keys, tokens and passwords in transit.": "Klucze chmurowe, klucze prywatne, tokeny i hasła w przesyłanych danych.",
  "Known attacks": "Znane ataki",
  "Signatures from the attack feed: unsafe deserialization, code execution, poisoned tools.": "Sygnatury z feedu ataków: niebezpieczna deserializacja, wykonanie kodu, zatrute narzędzia.",
  "Instruction hijacking": "Przejmowanie poleceń",
  "Phrases and hidden markup that try to override the agent's instructions.": "Zwroty i ukryte znaczniki, które próbują nadpisać polecenia agenta.",
  "AI review": "Ocena AI",
  "A local model scores untrusted text for manipulation. It can tighten a decision, never loosen one.": "Lokalny model ocenia niezaufaną treść pod kątem manipulacji. Może zaostrzyć decyzję, nigdy jej nie złagodzi.",
  "Block when risk is at least": "Blokuj, gdy ryzyko wynosi co najmniej",
  "Flag when risk is at least": "Oznaczaj, gdy ryzyko wynosi co najmniej",
  "Thresholds saved": "Zapisano progi",
  "Lower is stricter. Running on {engine}; if it fails, requests are {fallback}.": "Niższy próg oznacza większy rygor. Działa na: {engine}. Przy awarii żądania są {fallback}.",
  "the local scorer": "lokalny klasyfikator",
  "the main model server, or the local scorer if none is configured": "główny serwer modeli, a bez niego lokalny klasyfikator",
  "Use the profile's thresholds": "Użyj progów z profilu",
  "Thresholds follow the profile again": "Progi znów wynikają z profilu",

  // policy
  "active version": "aktywna wersja",
  "Validate": "Sprawdź poprawność",
  "Save as new version": "Zapisz jako nową wersję",
  "Saved as {v}": "Zapisano jako {v}",
  "Valid. Saving will activate it immediately.": "Poprawny. Zapis od razu go aktywuje.",
  "This file is the only source of rules. Saving here or editing it on disk has the same effect within a second. A broken file is rejected and the previous version stays in force.": "Ten plik to jedyne źródło reguł. Zapis tutaj i edycja pliku na dysku działają tak samo, w ciągu sekundy. Błędny plik jest odrzucany, a poprzednia wersja pozostaje w mocy.",
  "History": "Historia",
  "Rejected": "Odrzucona",
  "Restored from v{n}": "Przywrócona z v{n}",
  "Changed via {src}": "Zmiana: {src}",
  "console": "konsola",
  "file": "plik",
  "startup": "start systemu",
  "Restore": "Przywróć",
  "Restored v{n} as {v}": "Przywrócono v{n} jako {v}",
  "in force": "obowiązuje",

  // signatures
  "Loading the attack feed…": "Wczytywanie feedu ataków…",
  "{n} signatures": "Sygnatury: {n}",
  "feed": "feed",
  "from": "z",
  "{id} enabled": "{id} włączona",
  "{id} disabled": "{id} wyłączona",
  "{id} removed": "Usunięto {id}",
  "{id} added. It applies to the next request.": "Dodano {id}. Działa od następnego żądania.",
  "Remove": "Usuń",
  "Add a pattern": "Dodaj wzorzec",
  "Signature ID": "Identyfikator sygnatury",
  "What it catches": "Co wykrywa",
  "e.g. Requests to wire funds": "np. prośby o przelew środków",
  "Regular expression, case-insensitive": "Wyrażenie regularne, bez rozróżniania wielkości liter",
  "Severity": "Waga",
  "Sample text to try it on": "Przykładowy tekst do sprawdzenia",
  "Try it": "Wypróbuj",
  "Add to feed": "Dodaj do feedu",
  "Matches: {list}": "Dopasowania: {list}",
  "No match in the sample.": "Brak dopasowań w przykładzie.",
  "low": "niska",
  "medium": "średnia",
  "high": "wysoka",
  "critical": "krytyczna",

  // tasks
  "Tasks and their mandates": "Zadania i ich mandaty",
  "Task": "Zadanie",
  "For": "Dla kogo",
  "Data seen": "Przeczytane dane",
  "Status": "Status",
  "Calls": "Wywołania",
  "delegated by {id}": "zlecone przez {id}",
  "agent": "agent",
  "{a} of {b}": "{a} z {b}",
  "No tasks yet. Run a scenario or create one through the API.": "Nie ma jeszcze zadań. Uruchom scenariusz albo utwórz zadanie przez API.",
  "Revoke mandate": "Odbierz mandat",
  "Mandate revoked. Its lease no longer works.": "Mandat odebrany. Przepustka przestała działać.",
  "Most sensitive data read": "Najbardziej poufne przeczytane dane",
  "May read": "Może czytać",
  "May use": "Może używać",
  "May write to": "Może pisać do",
  "nothing": "niczego",
  "no e-mail recipients": "brak odbiorców e-mail",
  "Tokens": "Tokeny",
  "{a} spent of {b}": "zużyto {a} z {b}",
  "Expires": "Wygasa",
  "What happened": "Przebieg",
  "by": "reguła",
  "Read {label} data; the task is now {now}.": "Przeczytano dane: {label}. Zadanie ma teraz poziom: {now}.",
  "Tool ran": "Narzędzie wykonane",
  "Tool not called": "Narzędzie niewywołane",
  "Select a task to see its mandate and every decision made for it.": "Wybierz zadanie, aby zobaczyć jego mandat i wszystkie podjęte decyzje.",
  "active": "aktywne",
  "completed": "zakończone",
  "revoked": "odebrane",
  "contract review": "analiza umowy",
  "research": "research",
  "simulation": "symulacja",

  // tools
  "Tool definitions are pinned when first seen. If a server changes one later, the tool is hidden from agents and refused until someone approves the new text.": "Definicje narzędzi są zapamiętywane przy pierwszym użyciu. Jeśli serwer później którąś zmieni, narzędzie znika dla agentów i jest blokowane, dopóki ktoś nie zatwierdzi nowego opisu.",
  "Approved": "Zatwierdzone",
  "Quarantined": "W kwarantannie",
  "pinned": "odcisk",
  "Quarantine": "Kwarantanna",
  "Approve current text": "Zatwierdź obecny opis",
  "{id} quarantined": "{id} w kwarantannie",
  "{id} approved with its current definition": "{id} zatwierdzone z obecną definicją",
  "Changed to": "Zmieniono na",
  "Simulate a silent change on the server": "Zasymuluj cichą zmianę na serwerze",
  "The tool server changed a description. Watch it get quarantined.": "Serwer narzędzi zmienił opis. Zobacz, jak trafia do kwarantanny.",
  "Restore the server": "Przywróć serwer",
  "Tool server restored to its original definitions": "Przywrócono pierwotne definicje narzędzi",

  // budget
  "Race for one budget": "Wyścig o jeden budżet",
  "Agents start at the same moment and share a single pool. Each request reserves its maximum cost before the model is called.": "Agenci startują w tej samej chwili i dzielą jedną pulę. Każde żądanie rezerwuje swój maksymalny koszt, zanim zostanie wywołany model.",
  "Agents": "Agenci",
  "Pool, tokens": "Pula tokenów",
  "Per request": "Na żądanie",
  "Racing…": "Trwa wyścig…",
  "Start {n} agents": "Uruchom agentów: {n}",
  "Race finished": "Wyścig zakończony",
  "Uses the mock model and a throwaway user, so it does not touch real budgets or latency figures.": "Używa modelu testowego i jednorazowego użytkownika, więc nie wpływa na prawdziwe budżety ani pomiary czasu.",
  "Agents that ran": "Agenci, którzy się wykonali",
  "Stopped before the model call": "Zatrzymani przed wywołaniem modelu",
  "Committed": "Zaangażowane",
  "{a} of {b} tokens": "{a} z {b} tokenów",
  "Start a race to see how many agents get through and whether the pool ever goes negative.": "Uruchom wyścig, aby zobaczyć, ilu agentów przejdzie i czy pula kiedykolwiek spadnie poniżej zera.",
  "Budgets": "Budżety",
  "Scope": "Zakres",
  "Used": "Zużycie",
  "Spent": "Zużyte",
  "Held": "Zarezerwowane",
  "Limit": "Limit",
  "Waiting for reconciliation": "Czekające na rozliczenie",
  "The provider did not confirm these calls, so their tokens stay reserved.": "Dostawca nie potwierdził tych wywołań, więc ich tokeny pozostają zarezerwowane.",
  "{n} tokens for": "{n} tokenów dla",
  "Release": "Zwolnij",
  "Reservation released": "Rezerwacja zwolniona",

  // audit
  "Decision": "Decyzja",
  "Any": "Dowolna",
  "Rule": "Reguła",
  "Event": "Zdarzenie",
  "Download JSONL": "Pobierz JSONL",
  "Download CSV": "Pobierz CSV",
  "Entries can only be added. The database rejects edits and deletions, and evidence never contains the raw text that was checked.": "Wpisy można tylko dodawać. Baza danych odrzuca edycję i usuwanie, a dowody nigdy nie zawierają sprawdzanej treści.",
  "Time": "Czas",
  "Where": "Gdzie",

  // classification levels and profiles
  "public": "publiczne",
  "internal": "wewnętrzne",
  "confidential": "poufne",
  "secret": "tajne",
  "strict": "rygorystyczny",
  "balanced": "zrównoważony",
  "permissive": "liberalny",
  "blocked (on failure)": "blokowane",
  "allowed (on failure)": "przepuszczane",

  // channels, backends, stages, match types
  "model": "model",
  "tool": "narzędzie",
  "mcp": "MCP",
  "playground": "test",
  "model_register": "rejestracja modelu",
  "heuristic": "lokalny klasyfikator",
  "main": "główny serwer modeli",
  "override": "wymuszenie (demo)",
  "mandate": "mandat",
  "deterministic": "deterministyczne",
  "signatures": "sygnatury",
  "data flow": "przepływ danych",
  "semantic": "semantyczne",
  "budget": "budżet",
  "execute": "wykonanie",
  "model call": "wywołanie modelu",
  "output deterministic": "wyjście: deterministyczne",
  "output signatures": "wyjście: sygnatury",
  "result deterministic": "wynik: deterministyczne",
  "result signatures": "wynik: sygnatury",
  "result semantic": "wynik: semantyczne",
  "regex": "wyrażenie regularne",
  "pickle scan": "skan pickle",
  "component": "komponent",
  "gguf template": "szablon GGUF",
  "model source": "źródło modelu",
  "tool hash mismatch": "zmiana odcisku narzędzia",

  // reason codes and event kinds (humanised: lower case, spaces)
  "pii detected": "wykryto dane osobowe",
  "secret detected": "wykryto sekret",
  "prompt injection heuristic": "próba przejęcia poleceń",
  "known attack signature": "znana sygnatura ataku",
  "data flow violation": "naruszenie przepływu danych",
  "semantic manipulation": "manipulacja wykryta przez AI",
  "semantic suspicious": "treść podejrzana według AI",
  "semantic guard unavailable": "ocena AI niedostępna",
  "semantic ok": "ocena AI bez zastrzeżeń",
  "budget exceeded": "przekroczony budżet",
  "guard budget exceeded": "przekroczony budżet kontroli",
  "tool not in mandate": "narzędzie spoza mandatu",
  "resource not in mandate": "zasób spoza mandatu",
  "recipient not allowed": "niedozwolony odbiorca",
  "model not allowed": "niezatwierdzony model",
  "model not in mandate": "model spoza mandatu",
  "model unavailable": "model niedostępny",
  "tool quarantined": "narzędzie w kwarantannie",
  "tool definition changed": "zmieniona definicja narzędzia",
  "tool unavailable": "narzędzie niedostępne",
  "tool error": "błąd narzędzia",
  "unknown tool": "nieznane narzędzie",
  "memory cross case": "pamięć innej sprawy",
  "capability expired": "przepustka wygasła",
  "capability completed": "zadanie zakończone, przepustka nieważna",
  "capability revoked": "przepustka odebrana",
  "lease invalid": "nieprawidłowa przepustka",
  "lease agent mismatch": "przepustka innego agenta",
  "decision": "decyzja",
  "policy changed": "zmiana polityki",
  "policy rejected": "odrzucona polityka",
  "feed changed": "zmiana feedu",
  "feed rejected": "odrzucony feed",
  "task created": "utworzono zadanie",
  "task completed": "zakończono zadanie",
  "task delegated": "zlecono podzadanie",
  "task revoked": "odebrano mandat",
  "delegation denied": "odmowa delegacji",
  "tool approved": "zatwierdzono narzędzie",
  "tool quarantined ": "kwarantanna narzędzia",
  "simulation run": "symulacja",
  "semantic override": "wymuszenie oceny AI",
  "demo tool poisoned": "demo: zmiana narzędzia",
  "document label changed": "zmiana etykiety dokumentu",
  "reservation reconciled": "rozliczono rezerwację",
  "memory deleted": "usunięto wpis pamięci",
  "ignore instructions": "ignorowanie poleceń",
  "ignore instructions pl": "ignorowanie poleceń (PL)",
  "role override": "zmiana roli",
  "system prompt exfil": "wyciąganie promptu systemowego",
  "hidden ai note": "ukryta notatka dla AI",
  "concealment": "ukrywanie działań",

  // agent console
  "Be the agent": "Bądź agentem",
  "Allowed.": "Dozwolone.",
  "Allowed. The tool ran.": "Dozwolone. Narzędzie zostało wykonane.",
  "Ask the local model": "Zapytaj lokalny model",
  "Ask the model": "Model AI",
  "Client": "Klient",
  "Contract review for a client": "Analiza umowy klienta",
  "Public legal research": "Publiczny research prawny",
  "Do it": "Wykonaj",
  "Done.": "Gotowe.",
  "End the task": "Zakończ zadanie",
  "Most sensitive data read so far": "Najbardziej poufne dane przeczytane do tej pory",
  "New task": "Nowe zadanie",
  "Outside the mandate": "Poza mandatem",
  "Read": "Czytanie",
  "Read client A's contract": "Przeczytaj umowę klienta A",
  "Read client B's NDA": "Przeczytaj NDA klienta B",
  "Read the contract with a hidden instruction": "Przeczytaj umowę z ukrytym poleceniem",
  "Read the public NDA template": "Przeczytaj publiczny wzór NDA",
  "Run code": "Uruchom kod",
  "Save an internal memo": "Zapisz notatkę wewnętrzną",
  "Search and write": "Szukanie i zapis",
  "Search case law": "Szukaj w orzecznictwie",
  "Send an e-mail": "Wyślij e-mail",
  "Send outside": "Wysyłka na zewnątrz",
  "Start a task on the left first.": "Najpierw rozpocznij zadanie po lewej stronie.",
  "Start the task": "Rozpocznij zadanie",
  "The gateway refused the request before looking at it.": "Bramka odrzuciła żądanie, zanim w ogóle je sprawdziła.",
  "The mail server delivered it.": "Serwer pocztowy go wysłał.",
  "The mail server received nothing.": "Serwer pocztowy niczego nie dostał.",
  "The request never reached the tool.": "Żądanie nie dotarło do narzędzia.",
  "The task is over, but you can keep clicking: the old pass no longer opens anything.": "Zadanie się skończyło, ale możesz dalej klikać: stara przepustka niczego już nie otwiera.",
  "The tool ran, but its output was held back from the agent.": "Narzędzie zadziałało, ale jego wynik zatrzymano przed agentem.",
  "The tool ran; the dangerous part was removed before the agent saw it.": "Narzędzie zadziałało, a niebezpieczny fragment usunięto, zanim zobaczył go agent.",
  "You are the AI assistant now. Start a task, then try actions. Each click goes through the real gateway, exactly like an agent's request would, and you see what the guard decided and why.": "Teraz Ty jesteś asystentem AI. Rozpocznij zadanie i próbuj różnych akcji. Każde kliknięcie przechodzi przez prawdziwą bramkę, dokładnie jak żądanie agenta, a Ty widzisz, co postanowił strażnik i dlaczego.",
  "Your pass": "Twoja przepustka",
  "Your task now carries {level} data. From here on, nothing it produces may go anywhere cleared for less.": "Twoje zadanie zawiera teraz dane: {level}. Od tej chwili nic, co wytworzy, nie może trafić tam, gdzie dopuszczono mniej poufne dane.",
  "[content withheld from the agent]": "[treść zatrzymana przed agentem]",
  "not on your pass": "poza Twoją przepustką",
  "{n} external HTTP posts, {m} memos saved. Counted by the tools themselves.": "Wysyłek HTTP na zewnątrz: {n}, zapisanych notatek: {m}. Liczą same narzędzia.",
  "{tool} is not on this task's pass": "{tool} nie ma na przepustce tego zadania",
  "{r} is not an allowed recipient for this task": "{r} nie jest dozwolonym odbiorcą w tym zadaniu",
  "{p} is outside the files this task may read": "{p} jest poza plikami, które to zadanie może czytać",
  "model {m} is not approved": "model {m} nie jest zatwierdzony",
  "the {scope} budget has no room for this ({dim})": "w budżecie {scope} nie ma na to miejsca ({dim})",
  "{tool} is quarantined": "{tool} jest w kwarantannie",
  "tokens": "tokeny",
  "calls": "wywołania",
  "concurrency": "równoległość",
  "The model was given {doc} as context.": "Model dostał {doc} jako kontekst.",
  "Model": "Model",
  "cloud, public data only": "chmura, tylko dane publiczne",
  "our model server": "nasz serwer modeli",
  "test model, no AI": "model testowy, bez AI",
  "on this machine": "na tym komputerze",
  "not configured": "nieskonfigurowany",
  // sandbox
  "Code runs in a sandbox": "Kod uruchamia się w piaskownicy",
  "An agent is tricked into running code that tries to reach the network and to run forever. Each run happens in an isolated, throw-away container.": "Agent zostaje nakłoniony do uruchomienia kodu, który próbuje połączyć się z siecią i działać bez końca. Każde uruchomienie dzieje się w odizolowanym, jednorazowym kontenerze.",
  "Code execution": "Uruchamianie kodu",
  "When an agent runs code: block it, or run it in an isolated throw-away container with no network and tight limits.": "Gdy agent uruchamia kod: zablokuj go albo uruchom w odizolowanym, jednorazowym kontenerze bez sieci i z twardymi limitami.",
  "Run code (sandbox)": "Uruchom kod (piaskownica)",
  "Run code in the sandbox": "Uruchom kod w piaskownicy",
  "Run code that phones home": "Uruchom kod, który dzwoni do domu",
  "Data task (can run code)": "Zadanie na danych (może uruchamiać kod)",
  "exited cleanly": "zakończono poprawnie",
  "exited with an error": "zakończono błędem",
  "killed at the time limit": "ubity po przekroczeniu czasu",
  "killed at the memory limit": "ubity po przekroczeniu pamięci",
  "could not run": "nie udało się uruchomić",
  "skipped": "pominięto",
  "Sandbox: {status}, {ms} ms{net}": "Piaskownica: {status}, {ms} ms{net}",
  "; network was blocked": "; sieć była zablokowana",
  "Ran in an isolated container: {status}, {ms} ms{net}. Host untouched.": "Uruchomiono w odizolowanym kontenerze: {status}, {ms} ms{net}. Host nietknięty.",
  // guidance (Guide.jsx)
  "Start here": "Zacznij tutaj",
  "Passwords and keys": "Hasła i klucze",
  "Attacks on the agent": "Ataki na agenta",
  "Harmless (should pass)": "Nieszkodliwe (powinny przejść)",
  "ID card": "Dowód osobisty",
  "Address": "Adres",
  "Card number": "Numer karty",
  "Password in a sentence": "Hasło w zdaniu",
  "AWS key": "Klucz AWS",
  "Database URL": "Adres bazy z hasłem",
  "Ignore instructions": "Zignoruj polecenia",
  "Jailbreak (DAN)": "Jailbreak (DAN)",
  "Hidden in base64": "Ukryte w base64",
  "Exfiltration in a document": "Wyciek ukryty w dokumencie",
  "Wipe the disk": "Wyczyść dysk",
  "Reverse shell": "Reverse shell",
  "Password question": "Pytanie o hasło",
  "Ordinary request": "Zwykła prośba",
  "Article about attacks": "Artykuł o atakach",
  "It contains personal data.": "Zawiera dane osobowe.",
  "It contains a password, PIN or access key.": "Zawiera hasło, PIN albo klucz dostępu.",
  "It tries to take over the agent's instructions.": "Próbuje przejąć polecenia agenta.",
  "The AI review judged it as manipulation.": "Ocena AI uznała to za manipulację.",
  "It matches a known attack pattern.": "Pasuje do wzorca znanego ataku.",
  "Confidential data would end up somewhere it may not go.": "Poufne dane trafiłyby tam, gdzie nie wolno.",
  "Passed. No control found a problem, so the model would get this text unchanged.": "Przepuszczone. Żadna kontrola nie znalazła problemu, więc model dostałby ten tekst bez zmian.",
  "Passed with parts cut out. The model would only see the version below, with the sensitive parts masked.": "Przepuszczone po wycięciu fragmentów. Model zobaczyłby tylko wersję poniżej, z zamaskowanymi danymi.",
  "Stopped. Nothing would reach the model or the tool, and the attempt is in the audit log.": "Zatrzymane. Nic nie trafiłoby do modelu ani narzędzia, a próba jest zapisana w dzienniku audytu.",
  "Why": "Dlaczego",
  "Control": "Kontrola",
  "What the model would receive": "Co dostałby model",
  "AI review also looked at it: risk {risk} ({backend}).": "Ocena AI też to sprawdziła: ryzyko {risk} ({backend}).",
  "Want to see the policy change live? Switch the control that fired off, and the same text is checked again.": "Chcesz zobaczyć zmianę polityki na żywo? Wyłącz kontrolę, która zadziałała, a ten sam tekst zostanie sprawdzony ponownie.",
  "Turn off “{name}” and re-check": "Wyłącz „{name}” i sprawdź ponownie",
  "Switched off right now: {list}. Requests are not checked for this.": "Teraz wyłączone: {list}. Zapytania nie są pod tym kątem sprawdzane.",
  "Turn everything back on": "Włącz wszystko z powrotem",
  "…or type anything you like": "…albo wpisz cokolwiek chcesz",
  "Checking…": "Sprawdzam…",
  "Check it": "Sprawdź",
  "Ctrl+Enter also works. Nothing is executed, the gateway only decides.": "Działa też Ctrl+Enter. Nic się nie wykonuje, bramka tylko decyduje.",
  "Click an example on the left. The verdict appears here.": "Kliknij przykład po lewej. Werdykt pojawi się tutaj.",
  "Loading…": "Ładowanie…",
  "Text being checked": "Sprawdzany tekst",
  "Control “Personal data”": "Kontrola „Dane osobowe”",
  "Turn it off": "Wyłącz ją",
  "Turn it back on": "Włącz ją z powrotem",
  "Mode": "Tryb",
  "Policy version now in force:": "Obowiązująca wersja polityki:",
  "Copied": "Skopiowano",
  "Copy": "Kopiuj",
  "Check any text": "Sprawdź dowolny tekst",
  "Guardrails: deterministic and AI-based": "Zabezpieczenia deterministyczne i oparte na AI",
  "This is the fastest way to see the gateway work. Click an example, or write your own prompt. You get a decision (allowed, redacted or blocked), the reason in plain words, and exactly what the model would receive.": "To najszybszy sposób, żeby zobaczyć bramkę w akcji. Kliknij przykład albo wpisz własny prompt. Dostaniesz decyzję (dozwolone, zredagowane albo zablokowane), powód prostymi słowami i dokładnie to, co dostałby model.",
  "Change a rule and watch it apply immediately": "Zmień regułę i zobacz, że działa od razu",
  "Central policy, live configuration": "Centralna polityka, konfiguracja na żywo",
  "All rules live in one policy file. Switch the personal-data control off, or move it from redact to block: the same text is checked again with the new policy version, no restart.": "Wszystkie reguły są w jednym pliku polityki. Wyłącz kontrolę danych osobowych albo przełącz ją z redagowania na blokowanie: ten sam tekst zostanie sprawdzony ponownie z nową wersją polityki, bez restartu.",
  "More: “Controls” has every control and the strictness profile; “Policy file” lets you edit the YAML itself, break it on purpose and roll back.": "Więcej: w „Kontrolach” są wszystkie kontrole i profil surowości; w „Pliku polityki” możesz edytować sam YAML, celowo go zepsuć i przywrócić poprzednią wersję.",
  "Open Controls": "Otwórz Kontrole",
  "Open the policy file": "Otwórz plik polityki",
  "Run a full attack end to end": "Uruchom pełny atak od początku do końca",
  "Robustness, agent ↔ tool ↔ MCP": "Odporność: agent ↔ narzędzie ↔ MCP",
  "A scripted agent goes through the real gateway, database and tool service. Start with “Poisoned contract”: the document tells the agent to e-mail it outside. Watch the mail counter stay at zero.": "Oskryptowany agent przechodzi przez prawdziwą bramkę, bazę i usługę narzędzi. Zacznij od „Zatrutej umowy”: dokument każe agentowi wysłać go mailem na zewnątrz. Licznik maili zostaje na zerze.",
  "Go to scenarios": "Przejdź do scenariuszy",
  "Or drive the agent yourself": "Albo sam pokieruj agentem",
  "See every decision and export the audit log": "Zobacz każdą decyzję i wyeksportuj dziennik audytu",
  "Security reporting": "Raportowanie bezpieczeństwa",
  "“Live” shows decisions as they happen, what reached the tools, spend and the time each check adds. “Audit log” is append-only and exports to JSONL or CSV for the security team.": "„Na żywo” pokazuje decyzje w chwili ich podjęcia, co dotarło do narzędzi, koszty i czas dodawany przez każdą kontrolę. „Dziennik audytu” można tylko dopisywać i eksportować do JSONL lub CSV dla zespołu bezpieczeństwa.",
  "Open Live": "Otwórz Na żywo",
  "Open the audit log": "Otwórz dziennik audytu",
  "Try to overspend the budget": "Spróbuj przekroczyć budżet",
  "Budget and resource governance": "Budżet i kontrola zasobów",
  "Thirty agents race for one token pool. Each request reserves its cost before the model is called, so the pool never goes negative.": "Trzydziestu agentów ściga się o jedną pulę tokenów. Każde zapytanie rezerwuje koszt przed wywołaniem modelu, więc pula nigdy nie spada poniżej zera.",
  "Open Budget": "Otwórz Budżet",
  "Run the automated test suite": "Uruchom automatyczne testy",
  "Self-testing suite": "Zestaw autotestów",
  "Every control has cases that must pass and cases that must be stopped. Run them from the repository root:": "Każda kontrola ma przypadki, które muszą przejść, i takie, które muszą zostać zatrzymane. Uruchom je z katalogu głównego repozytorium:",
  "Without Docker for the app: make venv && make test. The input cases are listed in tests/cases/content.yaml and can be extended without code.": "Bez Dockera dla aplikacji: make venv && make test. Przypadki wejściowe są w tests/cases/content.yaml i można je dopisywać bez kodu.",
  "Mark as done": "Oznacz jako zrobione",
  "Aegis sits between AI agents and everything they touch: models, tools, MCP servers and other agents. Every request is checked against one central policy and is allowed, redacted or blocked. These six steps show all of it in about five minutes.": "Aegis stoi między agentami AI a wszystkim, czego dotykają: modelami, narzędziami, serwerami MCP i innymi agentami. Każde zapytanie jest sprawdzane według jednej centralnej polityki i zostaje przepuszczone, zredagowane albo zablokowane. Te sześć kroków pokazuje wszystko w około pięć minut.",
  "Progress": "Postęp",
  "{a} of {b} steps done": "Zrobione kroki: {a} z {b}",
  "Shows": "Pokazuje",
  "Every decision the gateway makes, as it happens, plus what actually reached the tools, the spend and the time each check adds.": "Każda decyzja bramki w chwili jej podjęcia, a do tego: co naprawdę dotarło do narzędzi, koszty i czas dodawany przez każdą kontrolę.",
  "Empty? Open “Run a scenario” or “Test an input”, then come back: the new rows appear here at once.": "Pusto? Otwórz „Scenariusze” albo „Sprawdź treść” i wróć: nowe wiersze pojawią się tu od razu.",
  "A red row means a blocked request; “never reached the tool” is the proof that it did not run.": "Czerwony wiersz to zablokowane zapytanie; „nie dotarło do narzędzia” to dowód, że się nie wykonało.",
  "Every agent task has a mandate: which files, tools and recipients it may use, its budget and its expiry.": "Każde zadanie agenta ma mandat: jakie pliki, narzędzia i odbiorców może użyć, jaki ma budżet i kiedy wygasa.",
  "Click a row to see its mandate and every decision made for it.": "Kliknij wiersz, żeby zobaczyć mandat i każdą decyzję podjętą dla tego zadania.",
  "“Revoke mandate” kills the agent's pass immediately; its next request is refused.": "„Odbierz mandat” natychmiast unieważnia przepustkę agenta; jego następne zapytanie zostanie odrzucone.",
  "The full, append-only record for the security team. The database refuses edits and deletions.": "Pełny zapis dla zespołu bezpieczeństwa, który można tylko dopisywać. Baza odrzuca edycję i usuwanie.",
  "Filter by decision or rule, e.g. Blocked + SEC-001.": "Filtruj po decyzji lub regule, np. Zablokowane + SEC-001.",
  "Click a row to see the evidence. Download JSONL or CSV for your SIEM.": "Kliknij wiersz, żeby zobaczyć dowody. Pobierz JSONL lub CSV do swojego SIEM.",
  "Switch each control on or off, choose redact or block, and set how strict the AI review is.": "Włączaj i wyłączaj kontrole, wybieraj redagowanie lub blokowanie i ustaw, jak surowa ma być ocena AI.",
  "Switch “Personal data” off, then check a PESEL in “Test an input”: it passes. Switch it back on.": "Wyłącz „Dane osobowe” i sprawdź PESEL w „Sprawdź treść”: przejdzie. Potem włącz z powrotem.",
  "Move the profile to Strict: redactions become blocks.": "Przełącz profil na „Rygorystyczny”: redakcje zmienią się w blokady.",
  "The single source of truth: policy/policy.yaml. Saving here or editing the file on disk takes effect within a second.": "Jedno źródło prawdy: policy/policy.yaml. Zapis tutaj albo edycja pliku na dysku działa w ciągu sekundy.",
  "Change something, Validate, then Save as new version.": "Zmień coś, kliknij Waliduj, potem Zapisz jako nową wersję.",
  "Break it on purpose (e.g. block_at_risk: 7): it is rejected and the previous version stays in force.": "Zepsuj go celowo (np. block_at_risk: 7): zmiana zostanie odrzucona, a poprzednia wersja dalej obowiązuje.",
  "Restore any earlier version from the history.": "Przywróć dowolną wcześniejszą wersję z historii.",
  "Patterns of known attacks, loaded from an external feed file (feeds/attacks.yaml) and reloaded live.": "Wzorce znanych ataków wczytywane z zewnętrznego pliku feedu (feeds/attacks.yaml) i przeładowywane na żywo.",
  "Add your own regex, try it on a sample, add it to the feed: it blocks from the next request.": "Dodaj własny regex, wypróbuj go na próbce i dodaj do feedu: blokuje od następnego zapytania.",
  "Switch one off to see the attack pass in “Test an input”.": "Wyłącz jedną sygnaturę i zobacz w „Sprawdź treść”, że atak przechodzi.",
  "MCP and tool definitions are pinned by hash when first seen. A silent change sends the tool to quarantine.": "Definicje narzędzi i MCP są przypinane hashem przy pierwszym użyciu. Cicha zmiana wysyła narzędzie do kwarantanny.",
  "Click “Simulate a silent change on the server” and watch the tool get quarantined.": "Kliknij „Zasymuluj cichą zmianę na serwerze” i zobacz, jak narzędzie trafia do kwarantanny.",
  "Approve the new text, or restore the server.": "Zatwierdź nowy opis albo przywróć serwer.",
  "You play the AI agent. Every click is a real request through the gateway, with a real task and a real lease.": "Grasz agenta AI. Każde kliknięcie to prawdziwe zapytanie przez bramkę, z prawdziwym zadaniem i przepustką.",
  "Start a contract-review task, read client A's contract, then try to e-mail it outside.": "Rozpocznij analizę umowy, przeczytaj umowę klienta A, a potem spróbuj wysłać ją mailem na zewnątrz.",
  "Read the contract with a hidden instruction and see what reaches you.": "Przeczytaj umowę z ukrytym poleceniem i zobacz, co do Ciebie dotrze.",
  "Scripted attacks that run end to end through the real gateway, database and tool service.": "Oskryptowane ataki, które przechodzą od początku do końca przez prawdziwą bramkę, bazę i usługę narzędzi.",
  "“Poisoned contract”: the mail counter must stay at 0.": "„Zatruta umowa”: licznik maili musi zostać na 0.",
  "“The AI detector misses”: the AI review is forced to say safe and the data-flow rule still blocks.": "„Detektor AI się myli”: ocena AI jest zmuszona powiedzieć „bezpieczne”, a reguła przepływu danych i tak blokuje.",
  "Check any text without running anything. You get the decision, the rule that fired and what the model would receive.": "Sprawdź dowolny tekst bez uruchamiania czegokolwiek. Dostaniesz decyzję, regułę, która zadziałała, i to, co dostałby model.",
  "Click an example, or paste your own prompt.": "Kliknij przykład albo wklej własny prompt.",
  "Pick where the text comes from and where it is going: confidential data heading outside is blocked.": "Wybierz, skąd pochodzi tekst i dokąd idzie: poufne dane wysyłane na zewnątrz są blokowane.",
  "Token, call and concurrency limits for each task, user and the whole gateway, enforced before the model is called.": "Limity tokenów, wywołań i równoległości dla każdego zadania, użytkownika i całej bramki, egzekwowane przed wywołaniem modelu.",
  "Start 30 agents on a 10,000-token pool: the overspend must be 0.": "Uruchom 30 agentów na puli 10 000 tokenów: przekroczenie musi wynieść 0.",
  "Lower a limit in “Policy file” and watch the next requests get 429.": "Obniż limit w „Pliku polityki” i zobacz, że kolejne zapytania dostają 429.",
  "Show tips for this page": "Pokaż wskazówki dla tej strony",
  "Tips for this page": "Wskazówki dla tej strony",
  "What is this?": "Co to jest?",
  "Next": "Dalej",
  "Hide tips": "Ukryj wskazówki",
  "1. Pick an example, or skip and write your own": "1. Wybierz przykład albo pomiń i wpisz własny",
  "2. Text to check": "2. Tekst do sprawdzenia",
  "3. Optional: where the text comes from and where it is going": "3. Opcjonalnie: skąd pochodzi tekst i dokąd idzie",
  "Example: choose “Confidential” and “E-mail outside the firm”: even a harmless sentence is blocked, because confidential data may not leave.": "Przykład: wybierz „Poufne” i „E-mail poza firmę”: nawet niewinne zdanie zostanie zablokowane, bo poufne dane nie mogą wyjść na zewnątrz.",
  "PESEL, NIP, ID card and passport numbers, addresses, card numbers, IBANs, e-mail addresses and phone numbers.": "PESEL, NIP, numery dowodu i paszportu, adresy, numery kart, IBAN, adresy e-mail i numery telefonów.",
  "Cloud keys, private keys, tokens, database URLs, and passwords or PINs, even written in a sentence.": "Klucze chmurowe, klucze prywatne, tokeny, adresy baz z hasłem oraz hasła i PIN-y, nawet wpisane w zdaniu.",
  "pesel": "PESEL",
  "nip": "NIP",
  "iban": "IBAN",
  "email": "e-mail",
  "phone": "telefon",
  "credit card": "numer karty",
  "id card": "numer dowodu osobistego",
  "passport": "numer paszportu",
  "address": "adres",
  "password": "hasło",
  "pin": "PIN",
  "connection string": "adres bazy z hasłem",
  "aws access key": "klucz AWS",
  "private key": "klucz prywatny",
  "jwt": "token JWT",
  "github token": "token GitHub",
  "slack token": "token Slack",
  "api key": "klucz API",
  "google api key": "klucz Google API",
  "password assignment": "przypisanie hasła",
  "jailbreak": "jailbreak",
  "jailbreak dan": "jailbreak (DAN)",
  "roleplay bypass": "obejście przez odgrywanie roli",
  "markdown exfil": "wyciek przez obrazek markdown",
  "system prompt exfil pl": "wyciąganie promptu systemowego (PL)",
  "obfuscated ignore instructions": "ukryte ignorowanie poleceń",
  "obfuscated jailbreak": "ukryty jailbreak",
  "obfuscated role override": "ukryta zmiana roli",
  "obfuscated system prompt exfil": "ukryte wyciąganie promptu",
  "Guide": "Przewodnik",
  "Test it": "Testuj",
  "Monitor": "Monitoruj",
  "AI control layer": "Warstwa kontroli AI",
  "Close menu": "Zamknij menu",
  "Open menu": "Otwórz menu",
  "{n} off": "{n} wył.",
  "local scorer": "lokalny klasyfikator",
  "Signatures": "Sygnatury",
  "Pick an example above, or type any prompt here…": "Wybierz przykład powyżej albo wpisz tu dowolny prompt…",
  "Ready. Press “Check it” to see what the gateway decides.": "Gotowe. Naciśnij „Sprawdź”, żeby zobaczyć decyzję bramki.",
  "1. Pick an example or type a prompt.  2. Press “Check it”.  The verdict appears here.": "1. Wybierz przykład albo wpisz prompt.\n2. Naciśnij „Sprawdź”.\nWerdykt pojawi się tutaj.",
  "Guide for the jury · about 5 minutes": "Przewodnik dla jury · ok. 5 minut",
  "See Aegis stop an attack, step by step": "Zobacz, jak Aegis zatrzymuje atak, krok po kroku",
  "Aegis sits between AI agents and everything they touch: models, tools, MCP servers and other agents. Every request is checked against one central policy and is allowed, redacted or blocked.": "Aegis stoi między agentami AI a wszystkim, czego dotykają: modelami, narzędziami, serwerami MCP i innymi agentami. Każde zapytanie jest sprawdzane według jednej centralnej polityki i zostaje przepuszczone, zredagowane albo zablokowane.",
  "goes through unchanged": "przechodzi bez zmian",
  "goes through with sensitive parts masked": "przechodzi z zamaskowanymi danymi",
  "never reaches the model or tool": "nie dociera do modelu ani narzędzia",
  "steps done": "kroków zrobionych",
  "Pick an example or write your own prompt, then press “Check it”. You get the decision, the reason in plain words, and exactly what the model would receive.": "Wybierz przykład albo wpisz własny prompt i naciśnij „Sprawdź”. Dostaniesz decyzję, powód prostymi słowami i dokładnie to, co dostałby model.",
  "Try this": "Spróbuj",
  "{n} requests were refused before the budget check:": "Zapytania odrzucone przed sprawdzeniem budżetu ({n}):",
  "The AI review found a password or key in it.": "Ocena AI znalazła w tym hasło albo klucz.",
};
