// Polish translations. Keys are the English source strings used in App.jsx.
export default {
  // navigation and shell
  "Watch": "Podgląd",
  "Configure": "Konfiguracja",
  "Prove": "Dowody",
  "Live": "Na żywo",
  "Tasks": "Zadania",
  "Audit log": "Dziennik audytu",
  "Controls": "Kontrole",
  "Policy file": "Plik polityki",
  "Attack signatures": "Sygnatury ataków",
  "Tools": "Narzędzia",
  "Run a scenario": "Scenariusze",
  "Test an input": "Sprawdź treść",
  "Budget": "Budżet",
  "Sections": "Sekcje",
  "Language": "Język",
  "Admin key": "Klucz administratora",
  "Current security posture": "Bieżący stan zabezpieczeń",
  "Gateway healthy": "Bramka działa",
  "Gateway degraded": "Bramka ma problem",
  "Connecting": "Łączenie",
  "Policy": "Polityka",
  "Profile": "Profil",
  "AI review on {model}": "Ocena AI: {model}",
  "Test mode: prompts go to OpenRouter (cloud)": "Tryb testowy: prompty idą do OpenRouter (chmura)",
  "AI review on the local scorer": "Ocena AI przez lokalny klasyfikator",
  "{n} attack signatures": "Sygnatur ataków: {n}",
  "AI review forced to “safe” (demo)": "Ocena AI wymuszona na „bezpieczne” (demo)",
  "Off: {list}": "Wyłączone: {list}",

  // decisions
  "Allowed": "Dozwolone",
  "Redacted": "Zredagowane",
  "Blocked": "Zablokowane",
  "allowed": "dozwolonych",
  "redacted": "zredagowanych",
  "blocked": "zablokowanych",
  "Redact": "Redaguj",
  "Block": "Blokuj",

  // live
  "Connecting to the gateway…": "Łączenie z bramką…",
  "No agent traffic yet. Run a scenario to see decisions here.": "Agenci jeszcze nic nie robili. Uruchom scenariusz, a decyzje pojawią się tutaj.",
  "decisions so far:": "decyzji do tej pory:",
  "Decisions as they happen": "Decyzje na bieżąco",
  "Streaming": "Na żywo",
  "tool ran": "narzędzie wykonane",
  "never reached the tool": "nie dotarło do narzędzia",
  "Waiting for the next request. Open “Run a scenario” in another tab and watch it arrive.": "Czekam na kolejne żądanie. Otwórz „Scenariusze” w innej karcie i obserwuj, jak spływają decyzje.",
  "What actually reached the tools": "Co naprawdę dotarło do narzędzi",
  "e-mails delivered by the mail server": "e-maili wysłanych przez serwer pocztowy",
  "External HTTP posts": "Wysyłki HTTP na zewnątrz",
  "Memos saved": "Zapisane notatki",
  "{n} calls": "wywołań: {n}",
  "Counted inside the tool service itself. A blocked request never increments these.": "Liczone wewnątrz usługi narzędzi. Zablokowane żądanie nigdy nie zwiększa tych liczników.",
  "The tool service is not responding.": "Usługa narzędzi nie odpowiada.",
  "Spend": "Wydatki",
  "Tokens spent": "Zużyte tokeny",
  "Held in reservations": "Zarezerwowane",
  "Estimated cost": "Szacowany koszt",
  "Active tasks": "Aktywne zadania",
  "Time added by checks": "Czas dodany przez kontrole",
  "milliseconds": "milisekundy",
  "Stage": "Etap",
  "median": "mediana",
  "Whole decision": "Cała decyzja",
  "Rules doing the most work": "Najczęściej działające reguły",
  "{used} of {limit} tokens used": "Zużyto {used} z {limit} tokenów",
  "{time}: {a} allowed, {r} redacted, {b} blocked": "{time}: dozwolone {a}, zredagowane {r}, zablokowane {b}",
  "Decisions per minute, last hour": "Decyzje na minutę, ostatnia godzina",

  // scenarios
  "Each scenario drives a scripted agent through the real gateway, database and tool service. Nothing is mocked except the agent's choices.": "Każdy scenariusz prowadzi zaprogramowanego agenta przez prawdziwą bramkę, bazę danych i usługę narzędzi. Symulowane są tylko decyzje samego agenta.",
  "Run": "Uruchom",
  "Running…": "Trwa…",
  "{name}: finished": "{name}: zakończono",
  "A normal day": "Zwykły dzień pracy",
  "The agent searches case law, reads the client's contract, asks the local model for risks and files a memo.": "Agent przeszukuje orzecznictwo, czyta umowę klienta, pyta lokalny model o ryzyka i zapisuje notatkę.",
  "Poisoned contract": "Zatruta umowa",
  "The contract hides an instruction to e-mail it to an outside address. The agent tries.": "W umowie ukryto polecenie wysłania jej na obcy adres. Agent próbuje to zrobić.",
  "The AI detector misses": "Detektor AI przeocza atak",
  "The semantic detector is forced to say “safe” and the recipient is one the mandate allows. Only data lineage is left to stop it.": "Detektor semantyczny ma wymuszone „bezpieczne”, a odbiorca jest dozwolony w mandacie. Zatrzymać wyciek może już tylko śledzenie pochodzenia danych.",
  "Wrong client's files": "Dokumenty innego klienta",
  "An agent working for client A reaches for client B's NDA, then tries a path trick.": "Agent pracujący dla klienta A sięga po NDA klienta B, a potem próbuje sztuczki ze ścieżką.",
  "Reused credentials": "Ponowne użycie przepustki",
  "The task ends, the agent keeps its lease and tries to use it again.": "Zadanie się kończy, agent zachowuje przepustkę i próbuje jej użyć ponownie.",
  "Tool changes after approval": "Narzędzie zmienione po zatwierdzeniu",
  "The MCP server silently rewrites a tool description to include an exfiltration instruction.": "Serwer MCP po cichu zmienia opis narzędzia i dopisuje polecenie wyniesienia danych.",
  "Model supply chain": "Łańcuch dostaw modeli",
  "Four models are registered: one clean, one with a pickle that imports os, one hit by CVE-2024-34359, one from a typosquatted host.": "Rejestrujemy cztery modele: czysty, z plikiem pickle importującym os, podatny na CVE-2024-34359 i pobrany z podrobionej domeny.",
  "Thirty agents, one budget": "Trzydziestu agentów, jeden budżet",
  "Thirty agents race for a 10,000-token pool at 1,000 tokens each.": "Trzydziestu agentów walczy o pulę 10 000 tokenów, po 1000 tokenów każdy.",
  "Decisions recorded by the gateway, in order": "Decyzje zapisane przez bramkę, w kolejności",
  "e-mails left the building.": "e-maili opuściło firmę.",
  "e-mail(s) reached the mail server.": "e-mail(e) dotarły do serwera pocztowego.",
  "tokens over budget.": "tokenów ponad budżet.",
  "{ran} agents ran, {stopped} were stopped before calling the model.": "Wykonało się {ran} agentów, {stopped} zatrzymano przed wywołaniem modelu.",
  "Rejected: {why}.": "Odrzucono: {why}.",
  "The tool ran.": "Narzędzie zostało wykonane.",
  "The tool was never called.": "Narzędzie nie zostało wywołane.",
  "Visible tools: {list}.": "Widoczne narzędzia: {list}.",
  "Also flagged: {list}.": "Oznaczono też: {list}.",
  "Rules that fired:": "Zadziałały reguły:",
  "The document was read, but its content was held back from the agent.": "Dokument odczytano, ale jego treść zatrzymano przed agentem.",
  "The document was read and handed over with the dangerous part removed.": "Dokument odczytano i przekazano bez niebezpiecznego fragmentu.",

  // scenario steps (from the backend)
  "search case law": "wyszukanie orzecznictwa",
  "read contract": "odczyt umowy",
  "summarise with local model": "streszczenie przez lokalny model",
  "save internal memo": "zapis notatki wewnętrznej",
  "read poisoned contract": "odczyt zatrutej umowy",
  "compromised agent tries to exfiltrate": "przejęty agent próbuje wynieść dane",
  "legit memo still works": "zwykła notatka nadal działa",
  "read poisoned contract (detector says SAFE)": "odczyt zatrutej umowy (detektor mówi „bezpieczne”)",
  "send contract to an ALLOWED external recipient": "wysyłka umowy do DOZWOLONEGO odbiorcy zewnętrznego",
  "read client B NDA": "odczyt NDA klienta B",
  "path traversal attempt": "próba obejścia ścieżką",
  "during task": "w trakcie zadania",
  "reuse lease after completion": "użycie przepustki po zakończeniu zadania",
  "tools/list (approved)": "tools/list (zatwierdzone)",
  "tools/list (after silent change)": "tools/list (po cichej zmianie)",
  "tools/call quarantined tool": "tools/call narzędzia w kwarantannie",
  "server reverted + admin re-approved": "serwer przywrócony i ponownie zatwierdzony",
  "safe model": "bezpieczny model",
  "pickle importing os.*": "pickle importujący os.*",
  "typosquat source": "podrobiona domena",

  // playground
  "Text to check": "Treść do sprawdzenia",
  "Where it comes from": "Skąd pochodzi",
  "Where it is going": "Dokąd trafia",
  "Most sensitive data the task has read": "Najbardziej poufne dane, które zadanie już przeczytało",
  "Check this input": "Sprawdź",
  "A dry run: the gateway decides, but no model or tool is called.": "Próba na sucho: bramka podejmuje decyzję, ale nie wywołuje modelu ani narzędzia.",
  "Checked. Nothing was executed.": "Sprawdzono. Nic nie zostało wykonane.",
  "A document or tool result the agent reads": "Dokument lub wynik narzędzia czytany przez agenta",
  "A message from the user": "Wiadomość od użytkownika",
  "Arguments the agent sends to a tool": "Argumenty wysyłane przez agenta do narzędzia",
  "The model's answer": "Odpowiedź modelu",
  "Nowhere, just inspect it": "Nigdzie, tylko sprawdź",
  "E-mail outside the firm": "E-mail poza firmę",
  "E-mail inside the firm": "E-mail wewnątrz firmy",
  "Post to an external URL": "Wysyłka na zewnętrzny adres URL",
  "Internal case notes": "Wewnętrzne notatki sprawy",
  "Case-law search query": "Zapytanie do bazy orzecznictwa",
  "Local model prompt": "Prompt do lokalnego modelu",
  "Nothing to stop": "Nie ma czego zatrzymywać",
  "decided in {ms} ms": "zdecydowała w {ms} ms",
  "What the agent would receive": "Co otrzymałby agent",
  "Write or paste anything, then check it. Try a PESEL number, a hidden instruction, or confidential data heading to an outside address.": "Wpisz lub wklej dowolną treść i sprawdź ją. Spróbuj numeru PESEL, ukrytego polecenia albo poufnych danych wysyłanych na zewnątrz.",
  "found {list}": "wykryto: {list}",
  "matched {list}": "dopasowano: {list}",
  "risk {risk} from {backend}": "ryzyko {risk} według: {backend}",
  "{level} data cannot go to {sink} (cleared for {clearance})": "dane {level} nie mogą trafić do {sink} (dopuszczone: {clearance})",

  // controls
  "Loading controls…": "Wczytywanie kontroli…",
  "Strictness": "Poziom rygoru",
  "Sets the defaults for every control below. A setting changed on a single control overrides it.": "Ustawia wartości domyślne dla wszystkich kontroli poniżej. Zmiana ustawienia pojedynczej kontroli ma pierwszeństwo.",
  "Switched to {p}": "Przełączono na: {p}",
  "{what}. Policy is now {v}.": "{what}. Aktualna polityka: {v}.",
  "on": "włączone",
  "off": "wyłączone",
  "Off. Requests are not checked for this.": "Wyłączone. Żądania nie są pod tym kątem sprawdzane.",
  "Task mandates": "Mandaty zadań",
  "Each task may only use its own tools, files and recipients, until it ends.": "Każde zadanie może używać tylko własnych narzędzi, plików i odbiorców, i tylko do swojego zakończenia.",
  "Data lineage": "Pochodzenie danych",
  "Once a task reads confidential data, it cannot send anything to a less trusted place.": "Gdy zadanie przeczyta poufne dane, nie może już niczego wysłać w mniej zaufane miejsce.",
  "Approved models only": "Tylko zatwierdzone modele",
  "Requests to models outside the list are refused.": "Żądania do modeli spoza listy są odrzucane.",
  "Personal data": "Dane osobowe",
  "PESEL, card numbers, IBANs, e-mail addresses and phone numbers.": "PESEL, numery kart, IBAN, adresy e-mail i numery telefonów.",
  "Credentials and keys": "Hasła i klucze",
  "Cloud keys, private keys, tokens and passwords in transit.": "Klucze chmurowe, klucze prywatne, tokeny i hasła w przesyłanych danych.",
  "Known attacks": "Znane ataki",
  "Signatures from the attack feed: unsafe deserialization, code execution, poisoned tools.": "Sygnatury z feedu ataków: niebezpieczna deserializacja, wykonanie kodu, zatrute narzędzia.",
  "Instruction hijacking": "Przejmowanie poleceń",
  "Phrases and hidden markup that try to override the agent's instructions.": "Zwroty i ukryte znaczniki, które próbują nadpisać polecenia agenta.",
  "AI review": "Ocena AI",
  "A local model scores untrusted text for manipulation. It can tighten a decision, never loosen one.": "Lokalny model ocenia niezaufaną treść pod kątem manipulacji. Może zaostrzyć decyzję, nigdy jej nie złagodzi.",
  "Block when risk is at least": "Blokuj, gdy ryzyko wynosi co najmniej",
  "Flag when risk is at least": "Oznaczaj, gdy ryzyko wynosi co najmniej",
  "Thresholds saved": "Zapisano progi",
  "Lower is stricter. Running on {engine}; if it fails, requests are {fallback}.": "Niższy próg oznacza większy rygor. Działa na: {engine}. Przy awarii żądania są {fallback}.",
  "the local scorer": "lokalny klasyfikator",
  "the main model server, or the local scorer if none is configured": "główny serwer modeli, a bez niego lokalny klasyfikator",
  "Use the profile's thresholds": "Użyj progów z profilu",
  "Thresholds follow the profile again": "Progi znów wynikają z profilu",

  // policy
  "active version": "aktywna wersja",
  "Validate": "Sprawdź poprawność",
  "Save as new version": "Zapisz jako nową wersję",
  "Saved as {v}": "Zapisano jako {v}",
  "Valid. Saving will activate it immediately.": "Poprawny. Zapis od razu go aktywuje.",
  "This file is the only source of rules. Saving here or editing it on disk has the same effect within a second. A broken file is rejected and the previous version stays in force.": "Ten plik to jedyne źródło reguł. Zapis tutaj i edycja pliku na dysku działają tak samo, w ciągu sekundy. Błędny plik jest odrzucany, a poprzednia wersja pozostaje w mocy.",
  "History": "Historia",
  "Rejected": "Odrzucona",
  "Restored from v{n}": "Przywrócona z v{n}",
  "Changed via {src}": "Zmiana: {src}",
  "console": "konsola",
  "file": "plik",
  "startup": "start systemu",
  "Restore": "Przywróć",
  "Restored v{n} as {v}": "Przywrócono v{n} jako {v}",
  "in force": "obowiązuje",

  // signatures
  "Loading the attack feed…": "Wczytywanie feedu ataków…",
  "{n} signatures": "Sygnatury: {n}",
  "feed": "feed",
  "from": "z",
  "{id} enabled": "{id} włączona",
  "{id} disabled": "{id} wyłączona",
  "{id} removed": "Usunięto {id}",
  "{id} added. It applies to the next request.": "Dodano {id}. Działa od następnego żądania.",
  "Remove": "Usuń",
  "Add a pattern": "Dodaj wzorzec",
  "Signature ID": "Identyfikator sygnatury",
  "What it catches": "Co wykrywa",
  "e.g. Requests to wire funds": "np. prośby o przelew środków",
  "Regular expression, case-insensitive": "Wyrażenie regularne, bez rozróżniania wielkości liter",
  "Severity": "Waga",
  "Sample text to try it on": "Przykładowy tekst do sprawdzenia",
  "Try it": "Wypróbuj",
  "Add to feed": "Dodaj do feedu",
  "Matches: {list}": "Dopasowania: {list}",
  "No match in the sample.": "Brak dopasowań w przykładzie.",
  "low": "niska",
  "medium": "średnia",
  "high": "wysoka",
  "critical": "krytyczna",

  // tasks
  "Tasks and their mandates": "Zadania i ich mandaty",
  "Task": "Zadanie",
  "For": "Dla kogo",
  "Data seen": "Przeczytane dane",
  "Status": "Status",
  "Calls": "Wywołania",
  "delegated by {id}": "zlecone przez {id}",
  "agent": "agent",
  "{a} of {b}": "{a} z {b}",
  "No tasks yet. Run a scenario or create one through the API.": "Nie ma jeszcze zadań. Uruchom scenariusz albo utwórz zadanie przez API.",
  "Revoke mandate": "Odbierz mandat",
  "Mandate revoked. Its lease no longer works.": "Mandat odebrany. Przepustka przestała działać.",
  "Most sensitive data read": "Najbardziej poufne przeczytane dane",
  "May read": "Może czytać",
  "May use": "Może używać",
  "May write to": "Może pisać do",
  "nothing": "niczego",
  "no e-mail recipients": "brak odbiorców e-mail",
  "Tokens": "Tokeny",
  "{a} spent of {b}": "zużyto {a} z {b}",
  "Expires": "Wygasa",
  "What happened": "Przebieg",
  "by": "reguła",
  "Read {label} data; the task is now {now}.": "Przeczytano dane: {label}. Zadanie ma teraz poziom: {now}.",
  "Tool ran": "Narzędzie wykonane",
  "Tool not called": "Narzędzie niewywołane",
  "Select a task to see its mandate and every decision made for it.": "Wybierz zadanie, aby zobaczyć jego mandat i wszystkie podjęte decyzje.",
  "active": "aktywne",
  "completed": "zakończone",
  "revoked": "odebrane",
  "contract review": "analiza umowy",
  "research": "research",
  "simulation": "symulacja",

  // tools
  "Tool definitions are pinned when first seen. If a server changes one later, the tool is hidden from agents and refused until someone approves the new text.": "Definicje narzędzi są zapamiętywane przy pierwszym użyciu. Jeśli serwer później którąś zmieni, narzędzie znika dla agentów i jest blokowane, dopóki ktoś nie zatwierdzi nowego opisu.",
  "Approved": "Zatwierdzone",
  "Quarantined": "W kwarantannie",
  "pinned": "odcisk",
  "Quarantine": "Kwarantanna",
  "Approve current text": "Zatwierdź obecny opis",
  "{id} quarantined": "{id} w kwarantannie",
  "{id} approved with its current definition": "{id} zatwierdzone z obecną definicją",
  "Changed to": "Zmieniono na",
  "Simulate a silent change on the server": "Zasymuluj cichą zmianę na serwerze",
  "The tool server changed a description. Watch it get quarantined.": "Serwer narzędzi zmienił opis. Zobacz, jak trafia do kwarantanny.",
  "Restore the server": "Przywróć serwer",
  "Tool server restored to its original definitions": "Przywrócono pierwotne definicje narzędzi",

  // budget
  "Race for one budget": "Wyścig o jeden budżet",
  "Agents start at the same moment and share a single pool. Each request reserves its maximum cost before the model is called.": "Agenci startują w tej samej chwili i dzielą jedną pulę. Każde żądanie rezerwuje swój maksymalny koszt, zanim zostanie wywołany model.",
  "Agents": "Agenci",
  "Pool, tokens": "Pula tokenów",
  "Per request": "Na żądanie",
  "Racing…": "Trwa wyścig…",
  "Start {n} agents": "Uruchom agentów: {n}",
  "Race finished": "Wyścig zakończony",
  "Uses the mock model and a throwaway user, so it does not touch real budgets or latency figures.": "Używa modelu testowego i jednorazowego użytkownika, więc nie wpływa na prawdziwe budżety ani pomiary czasu.",
  "Agents that ran": "Agenci, którzy się wykonali",
  "Stopped before the model call": "Zatrzymani przed wywołaniem modelu",
  "Committed": "Zaangażowane",
  "{a} of {b} tokens": "{a} z {b} tokenów",
  "Start a race to see how many agents get through and whether the pool ever goes negative.": "Uruchom wyścig, aby zobaczyć, ilu agentów przejdzie i czy pula kiedykolwiek spadnie poniżej zera.",
  "Budgets": "Budżety",
  "Scope": "Zakres",
  "Used": "Zużycie",
  "Spent": "Zużyte",
  "Held": "Zarezerwowane",
  "Limit": "Limit",
  "Waiting for reconciliation": "Czekające na rozliczenie",
  "The provider did not confirm these calls, so their tokens stay reserved.": "Dostawca nie potwierdził tych wywołań, więc ich tokeny pozostają zarezerwowane.",
  "{n} tokens for": "{n} tokenów dla",
  "Release": "Zwolnij",
  "Reservation released": "Rezerwacja zwolniona",

  // audit
  "Decision": "Decyzja",
  "Any": "Dowolna",
  "Rule": "Reguła",
  "Event": "Zdarzenie",
  "Download JSONL": "Pobierz JSONL",
  "Download CSV": "Pobierz CSV",
  "Entries can only be added. The database rejects edits and deletions, and evidence never contains the raw text that was checked.": "Wpisy można tylko dodawać. Baza danych odrzuca edycję i usuwanie, a dowody nigdy nie zawierają sprawdzanej treści.",
  "Time": "Czas",
  "Where": "Gdzie",

  // classification levels and profiles
  "public": "publiczne",
  "internal": "wewnętrzne",
  "confidential": "poufne",
  "secret": "tajne",
  "strict": "rygorystyczny",
  "balanced": "zrównoważony",
  "permissive": "liberalny",
  "blocked (on failure)": "blokowane",
  "allowed (on failure)": "przepuszczane",

  // channels, backends, stages, match types
  "model": "model",
  "tool": "narzędzie",
  "mcp": "MCP",
  "playground": "test",
  "model_register": "rejestracja modelu",
  "heuristic": "lokalny klasyfikator",
  "main": "główny serwer modeli",
  "override": "wymuszenie (demo)",
  "mandate": "mandat",
  "deterministic": "deterministyczne",
  "signatures": "sygnatury",
  "data flow": "przepływ danych",
  "semantic": "semantyczne",
  "budget": "budżet",
  "execute": "wykonanie",
  "model call": "wywołanie modelu",
  "output deterministic": "wyjście: deterministyczne",
  "output signatures": "wyjście: sygnatury",
  "result deterministic": "wynik: deterministyczne",
  "result signatures": "wynik: sygnatury",
  "result semantic": "wynik: semantyczne",
  "regex": "wyrażenie regularne",
  "pickle scan": "skan pickle",
  "component": "komponent",
  "gguf template": "szablon GGUF",
  "model source": "źródło modelu",
  "tool hash mismatch": "zmiana odcisku narzędzia",

  // reason codes and event kinds (humanised: lower case, spaces)
  "pii detected": "wykryto dane osobowe",
  "secret detected": "wykryto sekret",
  "prompt injection heuristic": "próba przejęcia poleceń",
  "known attack signature": "znana sygnatura ataku",
  "data flow violation": "naruszenie przepływu danych",
  "semantic manipulation": "manipulacja wykryta przez AI",
  "semantic suspicious": "treść podejrzana według AI",
  "semantic guard unavailable": "ocena AI niedostępna",
  "semantic ok": "ocena AI bez zastrzeżeń",
  "budget exceeded": "przekroczony budżet",
  "guard budget exceeded": "przekroczony budżet kontroli",
  "tool not in mandate": "narzędzie spoza mandatu",
  "resource not in mandate": "zasób spoza mandatu",
  "recipient not allowed": "niedozwolony odbiorca",
  "model not allowed": "niezatwierdzony model",
  "model not in mandate": "model spoza mandatu",
  "model unavailable": "model niedostępny",
  "tool quarantined": "narzędzie w kwarantannie",
  "tool definition changed": "zmieniona definicja narzędzia",
  "tool unavailable": "narzędzie niedostępne",
  "tool error": "błąd narzędzia",
  "unknown tool": "nieznane narzędzie",
  "memory cross case": "pamięć innej sprawy",
  "capability expired": "przepustka wygasła",
  "capability completed": "zadanie zakończone, przepustka nieważna",
  "capability revoked": "przepustka odebrana",
  "lease invalid": "nieprawidłowa przepustka",
  "lease agent mismatch": "przepustka innego agenta",
  "decision": "decyzja",
  "policy changed": "zmiana polityki",
  "policy rejected": "odrzucona polityka",
  "feed changed": "zmiana feedu",
  "feed rejected": "odrzucony feed",
  "task created": "utworzono zadanie",
  "task completed": "zakończono zadanie",
  "task delegated": "zlecono podzadanie",
  "task revoked": "odebrano mandat",
  "delegation denied": "odmowa delegacji",
  "tool approved": "zatwierdzono narzędzie",
  "tool quarantined ": "kwarantanna narzędzia",
  "simulation run": "symulacja",
  "semantic override": "wymuszenie oceny AI",
  "demo tool poisoned": "demo: zmiana narzędzia",
  "document label changed": "zmiana etykiety dokumentu",
  "reservation reconciled": "rozliczono rezerwację",
  "memory deleted": "usunięto wpis pamięci",
  "ignore instructions": "ignorowanie poleceń",
  "ignore instructions pl": "ignorowanie poleceń (PL)",
  "role override": "zmiana roli",
  "system prompt exfil": "wyciąganie promptu systemowego",
  "hidden ai note": "ukryta notatka dla AI",
  "concealment": "ukrywanie działań",

  // agent console
  "Be the agent": "Bądź agentem",
  "Allowed.": "Dozwolone.",
  "Allowed. The tool ran.": "Dozwolone. Narzędzie zostało wykonane.",
  "Ask the local model": "Zapytaj lokalny model",
  "Ask the model": "Model AI",
  "Client": "Klient",
  "Contract review for a client": "Analiza umowy klienta",
  "Public legal research": "Publiczny research prawny",
  "Do it": "Wykonaj",
  "Done.": "Gotowe.",
  "End the task": "Zakończ zadanie",
  "Most sensitive data read so far": "Najbardziej poufne dane przeczytane do tej pory",
  "New task": "Nowe zadanie",
  "Outside the mandate": "Poza mandatem",
  "Read": "Czytanie",
  "Read client A's contract": "Przeczytaj umowę klienta A",
  "Read client B's NDA": "Przeczytaj NDA klienta B",
  "Read the contract with a hidden instruction": "Przeczytaj umowę z ukrytym poleceniem",
  "Read the public NDA template": "Przeczytaj publiczny wzór NDA",
  "Run code": "Uruchom kod",
  "Save an internal memo": "Zapisz notatkę wewnętrzną",
  "Search and write": "Szukanie i zapis",
  "Search case law": "Szukaj w orzecznictwie",
  "Send an e-mail": "Wyślij e-mail",
  "Send outside": "Wysyłka na zewnątrz",
  "Start a task on the left first.": "Najpierw rozpocznij zadanie po lewej stronie.",
  "Start the task": "Rozpocznij zadanie",
  "The gateway refused the request before looking at it.": "Bramka odrzuciła żądanie, zanim w ogóle je sprawdziła.",
  "The mail server delivered it.": "Serwer pocztowy go wysłał.",
  "The mail server received nothing.": "Serwer pocztowy niczego nie dostał.",
  "The request never reached the tool.": "Żądanie nie dotarło do narzędzia.",
  "The task is over, but you can keep clicking: the old pass no longer opens anything.": "Zadanie się skończyło, ale możesz dalej klikać: stara przepustka niczego już nie otwiera.",
  "The tool ran, but its output was held back from the agent.": "Narzędzie zadziałało, ale jego wynik zatrzymano przed agentem.",
  "The tool ran; the dangerous part was removed before the agent saw it.": "Narzędzie zadziałało, a niebezpieczny fragment usunięto, zanim zobaczył go agent.",
  "You are the AI assistant now. Start a task, then try actions. Each click goes through the real gateway, exactly like an agent's request would, and you see what the guard decided and why.": "Teraz Ty jesteś asystentem AI. Rozpocznij zadanie i próbuj różnych akcji. Każde kliknięcie przechodzi przez prawdziwą bramkę, dokładnie jak żądanie agenta, a Ty widzisz, co postanowił strażnik i dlaczego.",
  "Your pass": "Twoja przepustka",
  "Your task now carries {level} data. From here on, nothing it produces may go anywhere cleared for less.": "Twoje zadanie zawiera teraz dane: {level}. Od tej chwili nic, co wytworzy, nie może trafić tam, gdzie dopuszczono mniej poufne dane.",
  "[content withheld from the agent]": "[treść zatrzymana przed agentem]",
  "not on your pass": "poza Twoją przepustką",
  "{n} external HTTP posts, {m} memos saved. Counted by the tools themselves.": "Wysyłek HTTP na zewnątrz: {n}, zapisanych notatek: {m}. Liczą same narzędzia.",
  "{tool} is not on this task's pass": "{tool} nie ma na przepustce tego zadania",
  "{r} is not an allowed recipient for this task": "{r} nie jest dozwolonym odbiorcą w tym zadaniu",
  "{p} is outside the files this task may read": "{p} jest poza plikami, które to zadanie może czytać",
  "model {m} is not approved": "model {m} nie jest zatwierdzony",
  "the {scope} budget has no room for this ({dim})": "w budżecie {scope} nie ma na to miejsca ({dim})",
  "{tool} is quarantined": "{tool} jest w kwarantannie",
  "tokens": "tokeny",
  "calls": "wywołania",
  "concurrency": "równoległość",
  "The model was given {doc} as context.": "Model dostał {doc} jako kontekst.",
  "Model": "Model",
  "cloud, public data only": "chmura, tylko dane publiczne",
  "our model server": "nasz serwer modeli",
  "test model, no AI": "model testowy, bez AI",
  "on this machine": "na tym komputerze",
  "not configured": "nieskonfigurowany",
  // sandbox
  "Code runs in a sandbox": "Kod uruchamia się w piaskownicy",
  "An agent is tricked into running code that tries to reach the network and to run forever. Each run happens in an isolated, throw-away container.": "Agent zostaje nakłoniony do uruchomienia kodu, który próbuje połączyć się z siecią i działać bez końca. Każde uruchomienie dzieje się w odizolowanym, jednorazowym kontenerze.",
  "Code execution": "Uruchamianie kodu",
  "When an agent runs code: block it, or run it in an isolated throw-away container with no network and tight limits.": "Gdy agent uruchamia kod: zablokuj go albo uruchom w odizolowanym, jednorazowym kontenerze bez sieci i z twardymi limitami.",
  "Run code (sandbox)": "Uruchom kod (piaskownica)",
  "Run code in the sandbox": "Uruchom kod w piaskownicy",
  "Run code that phones home": "Uruchom kod, który dzwoni do domu",
  "Data task (can run code)": "Zadanie na danych (może uruchamiać kod)",
  "exited cleanly": "zakończono poprawnie",
  "exited with an error": "zakończono błędem",
  "killed at the time limit": "ubity po przekroczeniu czasu",
  "killed at the memory limit": "ubity po przekroczeniu pamięci",
  "could not run": "nie udało się uruchomić",
  "skipped": "pominięto",
  "Sandbox: {status}, {ms} ms{net}": "Piaskownica: {status}, {ms} ms{net}",
  "; network was blocked": "; sieć była zablokowana",
  "Ran in an isolated container: {status}, {ms} ms{net}. Host untouched.": "Uruchomiono w odizolowanym kontenerze: {status}, {ms} ms{net}. Host nietknięty.",
  // guidance (Guide.jsx)
  "Start here": "Zacznij tutaj",
  "Passwords and keys": "Hasła i klucze",
  "Attacks on the agent": "Ataki na agenta",
  "Harmless (should pass)": "Nieszkodliwe (powinny przejść)",
  "ID card": "Dowód osobisty",
  "Address": "Adres",
  "Card number": "Numer karty",
  "Password in a sentence": "Hasło w zdaniu",
  "AWS key": "Klucz AWS",
  "Database URL": "Adres bazy z hasłem",
  "Ignore instructions": "Zignoruj polecenia",
  "Jailbreak (DAN)": "Jailbreak (DAN)",
  "Hidden in base64": "Ukryte w base64",
  "Exfiltration in a document": "Wyciek ukryty w dokumencie",
  "Wipe the disk": "Wyczyść dysk",
  "Reverse shell": "Reverse shell",
  "Password question": "Pytanie o hasło",
  "Ordinary request": "Zwykła prośba",
  "Article about attacks": "Artykuł o atakach",
  "It contains personal data.": "Zawiera dane osobowe.",
  "It contains a password, PIN or access key.": "Zawiera hasło, PIN albo klucz dostępu.",
  "It tries to take over the agent's instructions.": "Próbuje przejąć polecenia agenta.",
  "The AI review judged it as manipulation.": "Ocena AI uznała to za manipulację.",
  "It matches a known attack pattern.": "Pasuje do wzorca znanego ataku.",
  "Confidential data would end up somewhere it may not go.": "Poufne dane trafiłyby tam, gdzie nie wolno.",
  "Passed. No control found a problem, so the model would get this text unchanged.": "Przepuszczone. Żadna kontrola nie znalazła problemu, więc model dostałby ten tekst bez zmian.",
  "Passed with parts cut out. The model would only see the version below, with the sensitive parts masked.": "Przepuszczone po wycięciu fragmentów. Model zobaczyłby tylko wersję poniżej, z zamaskowanymi danymi.",
  "Stopped. Nothing would reach the model or the tool, and the attempt is in the audit log.": "Zatrzymane. Nic nie trafiłoby do modelu ani narzędzia, a próba jest zapisana w dzienniku audytu.",
  "Why": "Dlaczego",
  "Control": "Kontrola",
  "What the model would receive": "Co dostałby model",
  "AI review also looked at it: risk {risk} ({backend}).": "Ocena AI też to sprawdziła: ryzyko {risk} ({backend}).",
  "Want to see the policy change live? Switch the control that fired off, and the same text is checked again.": "Chcesz zobaczyć zmianę polityki na żywo? Wyłącz kontrolę, która zadziałała, a ten sam tekst zostanie sprawdzony ponownie.",
  "Turn off “{name}” and re-check": "Wyłącz „{name}” i sprawdź ponownie",
  "Switched off right now: {list}. Requests are not checked for this.": "Teraz wyłączone: {list}. Zapytania nie są pod tym kątem sprawdzane.",
  "Turn everything back on": "Włącz wszystko z powrotem",
  "…or type anything you like": "…albo wpisz cokolwiek chcesz",
  "Checking…": "Sprawdzam…",
  "Check it": "Sprawdź",
  "Ctrl+Enter also works. Nothing is executed, the gateway only decides.": "Działa też Ctrl+Enter. Nic się nie wykonuje, bramka tylko decyduje.",
  "Click an example on the left. The verdict appears here.": "Kliknij przykład po lewej. Werdykt pojawi się tutaj.",
  "Loading…": "Ładowanie…",
  "Text being checked": "Sprawdzany tekst",
  "Control “Personal data”": "Kontrola „Dane osobowe”",
  "Turn it off": "Wyłącz ją",
  "Turn it back on": "Włącz ją z powrotem",
  "Mode": "Tryb",
  "Policy version now in force:": "Obowiązująca wersja polityki:",
  "Copied": "Skopiowano",
  "Copy": "Kopiuj",
  "Check any text": "Sprawdź dowolny tekst",
  "Guardrails: deterministic and AI-based": "Zabezpieczenia deterministyczne i oparte na AI",
  "This is the fastest way to see the gateway work. Click an example, or write your own prompt. You get a decision (allowed, redacted or blocked), the reason in plain words, and exactly what the model would receive.": "To najszybszy sposób, żeby zobaczyć bramkę w akcji. Kliknij przykład albo wpisz własny prompt. Dostaniesz decyzję (dozwolone, zredagowane albo zablokowane), powód prostymi słowami i dokładnie to, co dostałby model.",
  "Change a rule and watch it apply immediately": "Zmień regułę i zobacz, że działa od razu",
  "Central policy, live configuration": "Centralna polityka, konfiguracja na żywo",
  "All rules live in one policy file. Switch the personal-data control off, or move it from redact to block: the same text is checked again with the new policy version, no restart.": "Wszystkie reguły są w jednym pliku polityki. Wyłącz kontrolę danych osobowych albo przełącz ją z redagowania na blokowanie: ten sam tekst zostanie sprawdzony ponownie z nową wersją polityki, bez restartu.",
  "More: “Controls” has every control and the strictness profile; “Policy file” lets you edit the YAML itself, break it on purpose and roll back.": "Więcej: w „Kontrolach” są wszystkie kontrole i profil surowości; w „Pliku polityki” możesz edytować sam YAML, celowo go zepsuć i przywrócić poprzednią wersję.",
  "Open Controls": "Otwórz Kontrole",
  "Open the policy file": "Otwórz plik polityki",
  "Run a full attack end to end": "Uruchom pełny atak od początku do końca",
  "Robustness, agent ↔ tool ↔ MCP": "Odporność: agent ↔ narzędzie ↔ MCP",
  "A scripted agent goes through the real gateway, database and tool service. Start with “Poisoned contract”: the document tells the agent to e-mail it outside. Watch the mail counter stay at zero.": "Oskryptowany agent przechodzi przez prawdziwą bramkę, bazę i usługę narzędzi. Zacznij od „Zatrutej umowy”: dokument każe agentowi wysłać go mailem na zewnątrz. Licznik maili zostaje na zerze.",
  "Go to scenarios": "Przejdź do scenariuszy",
  "Or drive the agent yourself": "Albo sam pokieruj agentem",
  "See every decision and export the audit log": "Zobacz każdą decyzję i wyeksportuj dziennik audytu",
  "Security reporting": "Raportowanie bezpieczeństwa",
  "“Live” shows decisions as they happen, what reached the tools, spend and the time each check adds. “Audit log” is append-only and exports to JSONL or CSV for the security team.": "„Na żywo” pokazuje decyzje w chwili ich podjęcia, co dotarło do narzędzi, koszty i czas dodawany przez każdą kontrolę. „Dziennik audytu” można tylko dopisywać i eksportować do JSONL lub CSV dla zespołu bezpieczeństwa.",
  "Open Live": "Otwórz Na żywo",
  "Open the audit log": "Otwórz dziennik audytu",
  "Try to overspend the budget": "Spróbuj przekroczyć budżet",
  "Budget and resource governance": "Budżet i kontrola zasobów",
  "Thirty agents race for one token pool. Each request reserves its cost before the model is called, so the pool never goes negative.": "Trzydziestu agentów ściga się o jedną pulę tokenów. Każde zapytanie rezerwuje koszt przed wywołaniem modelu, więc pula nigdy nie spada poniżej zera.",
  "Open Budget": "Otwórz Budżet",
  "Run the automated test suite": "Uruchom automatyczne testy",
  "Self-testing suite": "Zestaw autotestów",
  "Every control has cases that must pass and cases that must be stopped. Run them from the repository root:": "Każda kontrola ma przypadki, które muszą przejść, i takie, które muszą zostać zatrzymane. Uruchom je z katalogu głównego repozytorium:",
  "Without Docker for the app: make venv && make test. The input cases are listed in tests/cases/content.yaml and can be extended without code.": "Bez Dockera dla aplikacji: make venv && make test. Przypadki wejściowe są w tests/cases/content.yaml i można je dopisywać bez kodu.",
  "Mark as done": "Oznacz jako zrobione",
  "Aegis sits between AI agents and everything they touch: models, tools, MCP servers and other agents. Every request is checked against one central policy and is allowed, redacted or blocked. These six steps show all of it in about five minutes.": "Aegis stoi między agentami AI a wszystkim, czego dotykają: modelami, narzędziami, serwerami MCP i innymi agentami. Każde zapytanie jest sprawdzane według jednej centralnej polityki i zostaje przepuszczone, zredagowane albo zablokowane. Te sześć kroków pokazuje wszystko w około pięć minut.",
  "Progress": "Postęp",
  "{a} of {b} steps done": "Zrobione kroki: {a} z {b}",
  "Shows": "Pokazuje",
  "Every decision the gateway makes, as it happens, plus what actually reached the tools, the spend and the time each check adds.": "Każda decyzja bramki w chwili jej podjęcia, a do tego: co naprawdę dotarło do narzędzi, koszty i czas dodawany przez każdą kontrolę.",
  "Empty? Open “Run a scenario” or “Test an input”, then come back: the new rows appear here at once.": "Pusto? Otwórz „Scenariusze” albo „Sprawdź treść” i wróć: nowe wiersze pojawią się tu od razu.",
  "A red row means a blocked request; “never reached the tool” is the proof that it did not run.": "Czerwony wiersz to zablokowane zapytanie; „nie dotarło do narzędzia” to dowód, że się nie wykonało.",
  "Every agent task has a mandate: which files, tools and recipients it may use, its budget and its expiry.": "Każde zadanie agenta ma mandat: jakie pliki, narzędzia i odbiorców może użyć, jaki ma budżet i kiedy wygasa.",
  "Click a row to see its mandate and every decision made for it.": "Kliknij wiersz, żeby zobaczyć mandat i każdą decyzję podjętą dla tego zadania.",
  "“Revoke mandate” kills the agent's pass immediately; its next request is refused.": "„Odbierz mandat” natychmiast unieważnia przepustkę agenta; jego następne zapytanie zostanie odrzucone.",
  "The full, append-only record for the security team. The database refuses edits and deletions.": "Pełny zapis dla zespołu bezpieczeństwa, który można tylko dopisywać. Baza odrzuca edycję i usuwanie.",
  "Filter by decision or rule, e.g. Blocked + SEC-001.": "Filtruj po decyzji lub regule, np. Zablokowane + SEC-001.",
  "Click a row to see the evidence. Download JSONL or CSV for your SIEM.": "Kliknij wiersz, żeby zobaczyć dowody. Pobierz JSONL lub CSV do swojego SIEM.",
  "Switch each control on or off, choose redact or block, and set how strict the AI review is.": "Włączaj i wyłączaj kontrole, wybieraj redagowanie lub blokowanie i ustaw, jak surowa ma być ocena AI.",
  "Switch “Personal data” off, then check a PESEL in “Test an input”: it passes. Switch it back on.": "Wyłącz „Dane osobowe” i sprawdź PESEL w „Sprawdź treść”: przejdzie. Potem włącz z powrotem.",
  "Move the profile to Strict: redactions become blocks.": "Przełącz profil na „Rygorystyczny”: redakcje zmienią się w blokady.",
  "The single source of truth: policy/policy.yaml. Saving here or editing the file on disk takes effect within a second.": "Jedno źródło prawdy: policy/policy.yaml. Zapis tutaj albo edycja pliku na dysku działa w ciągu sekundy.",
  "Change something, Validate, then Save as new version.": "Zmień coś, kliknij Waliduj, potem Zapisz jako nową wersję.",
  "Break it on purpose (e.g. block_at_risk: 7): it is rejected and the previous version stays in force.": "Zepsuj go celowo (np. block_at_risk: 7): zmiana zostanie odrzucona, a poprzednia wersja dalej obowiązuje.",
  "Restore any earlier version from the history.": "Przywróć dowolną wcześniejszą wersję z historii.",
  "Patterns of known attacks, loaded from an external feed file (feeds/attacks.yaml) and reloaded live.": "Wzorce znanych ataków wczytywane z zewnętrznego pliku feedu (feeds/attacks.yaml) i przeładowywane na żywo.",
  "Add your own regex, try it on a sample, add it to the feed: it blocks from the next request.": "Dodaj własny regex, wypróbuj go na próbce i dodaj do feedu: blokuje od następnego zapytania.",
  "Switch one off to see the attack pass in “Test an input”.": "Wyłącz jedną sygnaturę i zobacz w „Sprawdź treść”, że atak przechodzi.",
  "MCP and tool definitions are pinned by hash when first seen. A silent change sends the tool to quarantine.": "Definicje narzędzi i MCP są przypinane hashem przy pierwszym użyciu. Cicha zmiana wysyła narzędzie do kwarantanny.",
  "Click “Simulate a silent change on the server” and watch the tool get quarantined.": "Kliknij „Zasymuluj cichą zmianę na serwerze” i zobacz, jak narzędzie trafia do kwarantanny.",
  "Approve the new text, or restore the server.": "Zatwierdź nowy opis albo przywróć serwer.",
  "You play the AI agent. Every click is a real request through the gateway, with a real task and a real lease.": "Grasz agenta AI. Każde kliknięcie to prawdziwe zapytanie przez bramkę, z prawdziwym zadaniem i przepustką.",
  "Start a contract-review task, read client A's contract, then try to e-mail it outside.": "Rozpocznij analizę umowy, przeczytaj umowę klienta A, a potem spróbuj wysłać ją mailem na zewnątrz.",
  "Read the contract with a hidden instruction and see what reaches you.": "Przeczytaj umowę z ukrytym poleceniem i zobacz, co do Ciebie dotrze.",
  "Scripted attacks that run end to end through the real gateway, database and tool service.": "Oskryptowane ataki, które przechodzą od początku do końca przez prawdziwą bramkę, bazę i usługę narzędzi.",
  "“Poisoned contract”: the mail counter must stay at 0.": "„Zatruta umowa”: licznik maili musi zostać na 0.",
  "“The AI detector misses”: the AI review is forced to say safe and the data-flow rule still blocks.": "„Detektor AI się myli”: ocena AI jest zmuszona powiedzieć „bezpieczne”, a reguła przepływu danych i tak blokuje.",
  "Check any text without running anything. You get the decision, the rule that fired and what the model would receive.": "Sprawdź dowolny tekst bez uruchamiania czegokolwiek. Dostaniesz decyzję, regułę, która zadziałała, i to, co dostałby model.",
  "Click an example, or paste your own prompt.": "Kliknij przykład albo wklej własny prompt.",
  "Pick where the text comes from and where it is going: confidential data heading outside is blocked.": "Wybierz, skąd pochodzi tekst i dokąd idzie: poufne dane wysyłane na zewnątrz są blokowane.",
  "Token, call and concurrency limits for each task, user and the whole gateway, enforced before the model is called.": "Limity tokenów, wywołań i równoległości dla każdego zadania, użytkownika i całej bramki, egzekwowane przed wywołaniem modelu.",
  "Start 30 agents on a 10,000-token pool: the overspend must be 0.": "Uruchom 30 agentów na puli 10 000 tokenów: przekroczenie musi wynieść 0.",
  "Lower a limit in “Policy file” and watch the next requests get 429.": "Obniż limit w „Pliku polityki” i zobacz, że kolejne zapytania dostają 429.",
  "Show tips for this page": "Pokaż wskazówki dla tej strony",
  "Tips for this page": "Wskazówki dla tej strony",
  "What is this?": "Co to jest?",
  "Next": "Dalej",
  "Hide tips": "Ukryj wskazówki",
  "1. Pick an example, or skip and write your own": "1. Wybierz przykład albo pomiń i wpisz własny",
  "2. Text to check": "2. Tekst do sprawdzenia",
  "3. Optional: where the text comes from and where it is going": "3. Opcjonalnie: skąd pochodzi tekst i dokąd idzie",
  "Example: choose “Confidential” and “E-mail outside the firm”: even a harmless sentence is blocked, because confidential data may not leave.": "Przykład: wybierz „Poufne” i „E-mail poza firmę”: nawet niewinne zdanie zostanie zablokowane, bo poufne dane nie mogą wyjść na zewnątrz.",
  "PESEL, NIP, ID card and passport numbers, addresses, card numbers, IBANs, e-mail addresses and phone numbers.": "PESEL, NIP, numery dowodu i paszportu, adresy, numery kart, IBAN, adresy e-mail i numery telefonów.",
  "Cloud keys, private keys, tokens, database URLs, and passwords or PINs, even written in a sentence.": "Klucze chmurowe, klucze prywatne, tokeny, adresy baz z hasłem oraz hasła i PIN-y, nawet wpisane w zdaniu.",
  "pesel": "PESEL",
  "nip": "NIP",
  "iban": "IBAN",
  "email": "e-mail",
  "phone": "telefon",
  "credit card": "numer karty",
  "id card": "numer dowodu osobistego",
  "passport": "numer paszportu",
  "address": "adres",
  "password": "hasło",
  "pin": "PIN",
  "connection string": "adres bazy z hasłem",
  "aws access key": "klucz AWS",
  "private key": "klucz prywatny",
  "jwt": "token JWT",
  "github token": "token GitHub",
  "slack token": "token Slack",
  "api key": "klucz API",
  "google api key": "klucz Google API",
  "password assignment": "przypisanie hasła",
  "jailbreak": "jailbreak",
  "jailbreak dan": "jailbreak (DAN)",
  "roleplay bypass": "obejście przez odgrywanie roli",
  "markdown exfil": "wyciek przez obrazek markdown",
  "system prompt exfil pl": "wyciąganie promptu systemowego (PL)",
  "obfuscated ignore instructions": "ukryte ignorowanie poleceń",
  "obfuscated jailbreak": "ukryty jailbreak",
  "obfuscated role override": "ukryta zmiana roli",
  "obfuscated system prompt exfil": "ukryte wyciąganie promptu",
  "Guide": "Przewodnik",
  "Test it": "Testuj",
  "Monitor": "Monitoruj",
  "AI control layer": "Warstwa kontroli AI",
  "Close menu": "Zamknij menu",
  "Open menu": "Otwórz menu",
  "{n} off": "{n} wył.",
  "local scorer": "lokalny klasyfikator",
  "Signatures": "Sygnatury",
  "Pick an example above, or type any prompt here…": "Wybierz przykład powyżej albo wpisz tu dowolny prompt…",
  "Ready. Press “Check it” to see what the gateway decides.": "Gotowe. Naciśnij „Sprawdź”, żeby zobaczyć decyzję bramki.",
  "1. Pick an example or type a prompt.  2. Press “Check it”.  The verdict appears here.": "1. Wybierz przykład albo wpisz prompt.\n2. Naciśnij „Sprawdź”.\nWerdykt pojawi się tutaj.",
  "Guide for the jury · about 5 minutes": "Przewodnik dla jury · ok. 5 minut",
  "See Aegis stop an attack, step by step": "Zobacz, jak Aegis zatrzymuje atak, krok po kroku",
  "Aegis sits between AI agents and everything they touch: models, tools, MCP servers and other agents. Every request is checked against one central policy and is allowed, redacted or blocked.": "Aegis stoi między agentami AI a wszystkim, czego dotykają: modelami, narzędziami, serwerami MCP i innymi agentami. Każde zapytanie jest sprawdzane według jednej centralnej polityki i zostaje przepuszczone, zredagowane albo zablokowane.",
  "goes through unchanged": "przechodzi bez zmian",
  "goes through with sensitive parts masked": "przechodzi z zamaskowanymi danymi",
  "never reaches the model or tool": "nie dociera do modelu ani narzędzia",
  "steps done": "kroków zrobionych",
  "Pick an example or write your own prompt, then press “Check it”. You get the decision, the reason in plain words, and exactly what the model would receive.": "Wybierz przykład albo wpisz własny prompt i naciśnij „Sprawdź”. Dostaniesz decyzję, powód prostymi słowami i dokładnie to, co dostałby model.",
  "Try this": "Spróbuj",
  "{n} requests were refused before the budget check:": "Zapytania odrzucone przed sprawdzeniem budżetu ({n}):",
  "The AI review found a password or key in it.": "Ocena AI znalazła w tym hasło albo klucz.",
  "Tests": "Sprawdza",
  "Pick a scenario and press Run. Each step is replayed here: what the agent sends, every check it passes or fails, and what reaches the tools.": "Wybierz scenariusz i naciśnij „Uruchom”. Każdy krok zostanie tu odtworzony: co wysyła agent, które kontrole przechodzi lub oblewa i co dociera do narzędzi.",
  "The app opens a task and issues a pass": "Aplikacja otwiera zadanie i wydaje przepustkę",
  "Before the agent does anything, the gateway writes down what this task may do. Every later request is checked against it.": "Zanim agent cokolwiek zrobi, bramka zapisuje, co wolno w tym zadaniu. Każde kolejne zapytanie jest z tym porównywane.",
  "{n} tokens, {c} calls": "{n} tokenów, {c} wywołań",
  "memo saved, nothing blocked that should pass.": "notatka zapisana, nic, co powinno przejść, nie zostało zablokowane.",
  "Replay": "Odtworzenie",
  "finished": "zakończone",
  "step {a} of {b}": "krok {a} z {b}",
  "Show all steps": "Pokaż wszystkie kroki",
  "Tools the agent can see": "Narzędzia widoczne dla agenta",
  "{n} agents got their tokens and ran": "Agenci, którzy dostali tokeny i ruszyli: {n}",
  "{n} stopped before calling the model (429)": "Zatrzymani przed wywołaniem modelu (429): {n}",
  "{n} refused for another reason": "Odrzuceni z innego powodu: {n}",
  "Shared pool": "Wspólna pula",
  "What is an attack signature?": "Czym jest sygnatura ataku?",
  "A fingerprint of an attack that is already known: a CVE, a public exploit, a technique seen in real incidents. Like an antivirus database, it does not need to understand the text, it recognises the pattern. Signatures come from a separate feed file (feeds/attacks.yaml, or a threat-intel URL), so the security team can update them without touching the policy or the code.": "To odcisk palca ataku, który jest już znany: CVE, publiczny exploit, technika z prawdziwych incydentów. Jak baza antywirusa: nie musi rozumieć tekstu, rozpoznaje wzorzec. Sygnatury pochodzą z osobnego pliku feedu (feeds/attacks.yaml albo adres threat-intel), więc zespół bezpieczeństwa aktualizuje je bez ruszania polityki i kodu.",
  "Text patterns": "Wzorce w tekście",
  "Reverse shells, curl | bash, rm -rf /, pickle.loads, trust_remote_code: checked in prompts, tool arguments, tool results and model answers.": "Reverse shelle, curl | bash, rm -rf /, pickle.loads, trust_remote_code: sprawdzane w promptach, argumentach narzędzi, wynikach narzędzi i odpowiedziach modelu.",
  "File scans": "Skanowanie plików",
  "Model files are scanned opcode by opcode for pickles that import os or subprocess. The file is never loaded.": "Pliki modeli są skanowane opcode po opcode w poszukiwaniu pickli importujących os lub subprocess. Plik nigdy nie jest wczytywany.",
  "Components and sources": "Komponenty i źródła",
  "Package versions with known CVEs, poisoned chat templates, models from typosquatted hosts, MCP tools changed after approval.": "Wersje pakietów ze znanymi CVE, zatrute szablony czatu, modele z podrobionych domen, narzędzia MCP zmienione po zatwierdzeniu.",
  "checked when a model or tool is registered": "sprawdzane przy rejestracji modelu lub narzędzia",
  "Example": "Przykład",
  "What are tools here?": "Czym są tu narzędzia?",
  "Tools are what an agent can do in the world: read a document, search, send an e-mail, post to a URL, run code. They live behind MCP servers or APIs. The agent never calls them directly: only the gateway holds the secret the tool service accepts, so every call must pass the checks first.": "Narzędzia to to, co agent może zrobić w świecie: przeczytać dokument, wyszukać, wysłać e-mail, wysłać dane pod adres URL, uruchomić kod. Stoją za serwerami MCP albo API. Agent nigdy nie woła ich bezpośrednio: tylko bramka ma sekret, który akceptuje usługa narzędzi, więc każde wywołanie musi najpierw przejść kontrole.",
  "Agent": "Agent",
  "pass, content, data flow, budget": "przepustka, treść, przepływ danych, budżet",
  "Tool service": "Usługa narzędzi",
  "Sandbox": "Piaskownica",
  "only code.run: a throw-away container, no network": "tylko code.run: jednorazowy kontener bez sieci",
  "This page guards against a different trick: tool poisoning. A server can silently change a tool's description to slip instructions to the agent. Each definition is pinned by its hash when first seen; if it changes, the tool is hidden and refused until someone approves the new text.": "Ta strona chroni przed innym trikiem: zatruciem narzędzia. Serwer może po cichu zmienić opis narzędzia, żeby przemycić agentowi polecenia. Każda definicja jest przypinana hashem przy pierwszym użyciu; jeśli się zmieni, narzędzie jest ukrywane i odrzucane, dopóki ktoś nie zatwierdzi nowego opisu.",
  "How a request pays": "Jak zapytanie płaci za siebie",
  "1. Reserve": "1. Rezerwacja",
  "Before the model is called, the gateway reserves the request's maximum cost (prompt + max_tokens) in every budget it belongs to: the task, the user and the whole gateway. One atomic database update; if any of them has no room, the request gets 429 and the model is never called.": "Zanim model zostanie wywołany, bramka rezerwuje maksymalny koszt zapytania (prompt + max_tokens) w każdym budżecie, do którego ono należy: zadania, użytkownika i całej bramki. Jedna atomowa operacja w bazie; jeśli w którymś brakuje miejsca, zapytanie dostaje 429 i model nie jest wołany.",
  "2. Run": "2. Wykonanie",
  "Only a request holding a reservation is sent to the model or tool.": "Do modelu lub narzędzia trafia tylko zapytanie, które ma rezerwację.",
  "3. Settle": "3. Rozliczenie",
  "The real usage is charged and the unused part of the reservation goes back to the pool.": "Naliczane jest faktyczne zużycie, a niewykorzystana część rezerwacji wraca do puli.",
  "Why not just check “is there room?” first: thirty agents asking at the same moment would all see room and all spend. Reserving first makes that impossible.": "Dlaczego nie wystarczy sprawdzić „czy jest miejsce?”: trzydziestu agentów pytających w tej samej chwili zobaczyłoby miejsce i wszyscy by wydali. Rezerwacja z góry to wyklucza.",
  "how many start at once": "ilu startuje naraz",
  "shared budget": "wspólny budżet",
  "max_tokens of each": "max_tokens każdego",
  "With these numbers at most {fit} of {n} agents fit in the pool. The rest must be stopped, and the pool must never go below zero.": "Przy tych liczbach w puli zmieści się najwyżej {fit} z {n} agentów. Reszta musi zostać zatrzymana, a pula nie może spaść poniżej zera.",
  "Start the race. Each dot will be one agent: green got its tokens, red was stopped before calling the model.": "Uruchom wyścig. Każda kropka to jeden agent: zielony dostał tokeny, czerwony został zatrzymany przed wywołaniem modelu.",
  "Budgets in force": "Obowiązujące budżety",
  "set in the policy file, section budgets": "ustawiane w pliku polityki, sekcja budgets",
  "The agent searches case law, reads the client's contract, asks the model for risks and files a memo.": "Agent szuka orzecznictwa, czyta umowę klienta, pyta model o ryzyka i zapisuje notatkę.",
  "Nothing is over-blocked: legitimate work goes through every check.": "Nic nie jest blokowane na wyrost: zwykła praca przechodzi przez wszystkie kontrole.",
  "The contract hides an instruction to e-mail it to an outside address. The agent obeys and tries.": "W umowie ukryto polecenie, żeby wysłać ją na zewnętrzny adres. Agent się słucha i próbuje.",
  "Prompt injection in a document, exfiltration by e-mail.": "Prompt injection w dokumencie, wyciek przez e-mail.",
  "The AI review is forced to say “safe” and the recipient is one the mandate allows. Only data lineage is left to stop it.": "Ocena AI jest zmuszona powiedzieć „bezpieczne”, a odbiorca jest dozwolony w mandacie. Zatrzymać to może już tylko pochodzenie danych.",
  "Defence in depth: deterministic data-flow rule behind the AI.": "Obrona warstwowa: deterministyczna reguła przepływu danych za AI.",
  "Least privilege: files outside the task's mandate.": "Najmniejsze uprawnienia: pliki spoza mandatu zadania.",
  "The task ends, the agent keeps its pass and tries to use it again.": "Zadanie się kończy, agent zachowuje przepustkę i próbuje jej użyć ponownie.",
  "Short-lived, task-bound credentials.": "Krótkotrwałe poświadczenia związane z zadaniem.",
  "MCP tool poisoning (“rug pull”), hash pinning and quarantine.": "Zatrucie narzędzia MCP („rug pull”), przypinanie hashem i kwarantanna.",
  "Unsafe deserialization, vulnerable packages, typosquatting.": "Niebezpieczna deserializacja, podatne pakiety, typosquatting.",
  "Malicious code execution, runaway compute.": "Złośliwy kod, niekontrolowane zużycie mocy.",
  "Budget governance under concurrency.": "Kontrola budżetu przy współbieżności.",
  "Step 1 of 2": "Krok 1 z 2",
  "Choose your mission": "Wybierz misję",
  "You play an AI agent. The app opens a task for you and the gateway issues a pass: what you may read, use and send, for how long and for how many tokens. Then you try things, legal and not, and watch each request go through the gateway.": "Grasz agenta AI. Aplikacja otwiera dla Ciebie zadanie, a bramka wydaje przepustkę: co możesz czytać, czego używać i dokąd wysyłać, na jak długo i za ile tokenów. Potem próbujesz różnych rzeczy, dozwolonych i nie, i patrzysz, jak każde zapytanie przechodzi przez bramkę.",
  "Your mission": "Twoja misja",
  "Hide details": "Ukryj szczegóły",
  "Change the details": "Zmień szczegóły",
  "What happened, request by request": "Co się stało, zapytanie po zapytaniu",
  "newest first": "najnowsze na górze",
  "Press “Do it” on any action. Its whole path through the gateway appears here.": "Naciśnij „Wykonaj” przy dowolnej akcji. Cała jej droga przez bramkę pojawi się tutaj.",
  "Contract review for client A": "Analiza umowy klienta A",
  "A law firm's assistant. Client A asked for a risk memo on their acquisition contract. Your pass lets you read client A's files, search case law, ask the model, save memos and e-mail people at the firm or at client A.": "Asystent kancelarii. Klient A poprosił o notatkę o ryzykach w umowie przejęcia. Przepustka pozwala czytać pliki klienta A, szukać orzecznictwa, pytać model, zapisywać notatki i wysyłać maile do osób w kancelarii lub u klienta A.",
  "An analyst's assistant that may run Python. Code never runs on the server: each run gets its own throw-away container with no network.": "Asystent analityka, który może uruchamiać Pythona. Kod nigdy nie działa na serwerze: każde uruchomienie dostaje własny jednorazowy kontener bez sieci.",
  "A research assistant with public sources only. It may not touch any client's files.": "Asystent researchu wyłącznie na publicznych źródłach. Nie może dotykać plików żadnego klienta.",
  "Normal work": "Normalna praca",
  "What the task is for. These should go through.": "Do tego służy zadanie. To powinno przejść.",
  "Allowed. The document is confidential, so from now on the whole task counts as confidential.": "Dozwolone. Dokument jest poufny, więc od teraz całe zadanie liczy się jako poufne.",
  "Allowed: research is on the pass.": "Dozwolone: research jest na przepustce.",
  "Ask the model about the contract": "Zapytaj model o umowę",
  "The last document you read goes to the model as context, checked like any untrusted input.": "Ostatnio przeczytany dokument trafia do modelu jako kontekst i jest sprawdzany jak każde niezaufane wejście.",
  "Internal notes may hold confidential data.": "Notatki wewnętrzne mogą zawierać poufne dane.",
  "E-mail a colleague at the firm": "Wyślij maila do kolegi z kancelarii",
  "Internal mail is cleared for confidential data.": "Poczta wewnętrzna jest dopuszczona do poufnych danych.",
  "Run a calculation in the sandbox": "Uruchom obliczenia w piaskownicy",
  "Only on the data task. It runs in an isolated container.": "Tylko w zadaniu na danych. Działa w odizolowanym kontenerze.",
  "Try to break the rules": "Spróbuj złamać zasady",
  "What a hijacked or careless agent would do. Each should be stopped, and you see where.": "To, co zrobiłby przejęty albo nieostrożny agent. Każda z tych akcji powinna zostać zatrzymana, a Ty widzisz, w którym miejscu.",
  "Read a contract with a hidden instruction": "Przeczytaj umowę z ukrytym poleceniem",
  "The file tells the agent to e-mail it outside. The hidden instruction is cut out or the content withheld.": "Plik każe agentowi wysłać go na zewnątrz. Ukryte polecenie zostaje wycięte albo treść wstrzymana.",
  "E-mail the contract to an outside address": "Wyślij umowę na zewnętrzny adres",
  "The recipient is not on the pass. The mail server must receive nothing.": "Odbiorcy nie ma na przepustce. Serwer pocztowy nie może nic dostać.",
  "E-mail client A after reading confidential data": "Wyślij maila do klienta A po przeczytaniu poufnych danych",
  "The recipient IS allowed, but the task has read confidential data and outside mail is cleared for public only. Read client A's contract first.": "Odbiorca JEST dozwolony, ale zadanie przeczytało poufne dane, a poczta na zewnątrz jest dopuszczona tylko do danych publicznych. Najpierw przeczytaj umowę klienta A.",
  "Client B's files are outside this task's pass.": "Pliki klienta B są poza przepustką tego zadania.",
  "Upload to an external website": "Wyślij na zewnętrzną stronę",
  "This tool is not on the pass at all.": "Tego narzędzia w ogóle nie ma na przepustce.",
  "Send the model a password": "Wyślij modelowi hasło",
  "A password in the prompt never reaches the model.": "Hasło w prompcie nigdy nie dociera do modelu.",
  "On the data task it runs in the sandbox, where the network is cut. Elsewhere code is not on the pass.": "W zadaniu na danych uruchamia się w piaskownicy, gdzie sieć jest odcięta. W innych zadaniach kodu nie ma na przepustce.",
  "Checks in order": "Kontrole po kolei",
  "Refused": "Odrzucono",
  "Nothing ran; this is the gateway's refusal.": "Nic się nie wykonało; to odmowa bramki.",
  "The agent {what}": "Agent {what}",
  "It ran.": "Wykonało się.",
  "It never ran: the tool or model was not called.": "Nic się nie wykonało: narzędzie ani model nie zostały wywołane.",
  "What the agent got back": "Co agent dostał z powrotem",
  "Pass": "Przepustka",
  "Is this tool, file or recipient on the task's mandate?": "Czy to narzędzie, plik albo odbiorca są w mandacie zadania?",
  "Does it match a signature from the attack feed?": "Czy pasuje do sygnatury z feedu ataków?",
  "Patterns": "Wzorce",
  "Personal data, passwords and keys, injection phrases.": "Dane osobowe, hasła i klucze, frazy przejmujące polecenia.",
  "Data flow": "Przepływ danych",
  "May data this confidential go to this destination?": "Czy dane o tej poufności mogą trafić w to miejsce?",
  "A model scores the text for manipulation.": "Model ocenia tekst pod kątem manipulacji.",
  "Tokens and calls are reserved before anything runs.": "Tokeny i wywołania są rezerwowane, zanim cokolwiek się wykona.",
  "Runs": "Wykonanie",
  "Only now is the tool or model actually called.": "Dopiero teraz narzędzie lub model są naprawdę wywoływane.",
  "Result check": "Kontrola wyniku",
  "The answer is checked before the agent sees it.": "Odpowiedź jest sprawdzana, zanim zobaczy ją agent.",
  "The agent looks for court rulings on break fees, a normal research step.": "Agent szuka orzeczeń o opłatach za zerwanie umowy, zwykły krok researchu.",
  "It opens the client's contract. The document is CONFIDENTIAL, so the task becomes confidential too.": "Otwiera umowę klienta. Dokument jest POUFNY, więc zadanie też staje się poufne.",
  "It asks the on-prem model for the main risks, with the contract as context.": "Pyta model działający lokalnie o główne ryzyka, z umową jako kontekstem.",
  "It files an internal memo. Internal notes are cleared for confidential data.": "Zapisuje notatkę wewnętrzną. Notatki wewnętrzne są dopuszczone do poufnych danych.",
  "The contract contains a hidden instruction: e-mail the agreement to an outside address.": "Umowa zawiera ukryte polecenie: wyślij ją na zewnętrzny adres.",
  "The agent obeys the hidden instruction and tries to e-mail the contract to the attacker.": "Agent wykonuje ukryte polecenie i próbuje wysłać umowę atakującemu.",
  "Normal work is not affected: the agent can still save its memo.": "Zwykła praca działa dalej: agent nadal może zapisać notatkę.",
  "The AI detector is forced to say the document is safe. It is still confidential.": "Detektor AI jest zmuszony uznać dokument za bezpieczny. Nadal jest poufny.",
  "The recipient is on the task's allow-list, so the mandate alone would let it through.": "Odbiorca jest na liście dozwolonych, więc sam mandat by to przepuścił.",
  "The task is for client A. The agent reaches for client B's file.": "Zadanie dotyczy klienta A. Agent sięga po plik klienta B.",
  "It tries a path trick (../) to escape client A's folder.": "Próbuje sztuczki ze ścieżką (../), żeby wyjść z folderu klienta A.",
  "A normal call while the task is active.": "Zwykłe wywołanie, gdy zadanie jest aktywne.",
  "The task is finished, but the agent kept its pass and tries to send an e-mail with it.": "Zadanie jest zakończone, ale agent zachował przepustkę i próbuje nią wysłać maila.",
  "The agent asks the MCP server which tools it may use. All definitions match their pinned hashes.": "Agent pyta serwer MCP, jakich narzędzi może użyć. Wszystkie definicje zgadzają się z przypiętymi hashami.",
  "The server silently rewrote legal_db.search's description. Its hash no longer matches, so it is hidden.": "Serwer po cichu przepisał opis legal_db.search. Hash się nie zgadza, więc narzędzie jest ukryte.",
  "The agent calls the changed tool anyway. Its new description now tells agents to mail documents out.": "Agent i tak woła zmienione narzędzie. Jego nowy opis każe agentom wysyłać dokumenty na zewnątrz.",
  "Someone registers a model before agents may use it. Aegis scans its source, packages and files.": "Ktoś rejestruje model, zanim agenci będą mogli go użyć. Aegis skanuje jego źródło, pakiety i pliki.",
  "Ordinary data work: the code only does arithmetic.": "Zwykła praca na danych: kod tylko liczy.",
  "Injected code tries to send data to the attacker's server.": "Wstrzyknięty kod próbuje wysłać dane na serwer atakującego.",
  "A runaway loop that would burn compute forever.": "Nieskończona pętla, która paliłaby moc obliczeniową w nieskończoność.",
  "Expected: everything allowed": "Oczekiwane: wszystko dozwolone",
  "Expected: the attack is stopped": "Oczekiwane: atak zatrzymany",
  "Expected: contained, not executed on the host": "Oczekiwane: odizolowane, nie na serwerze",
  "should pass": "powinno przejść",
  "should be contained": "powinno zostać odizolowane",
  "should be stopped": "powinno zostać zatrzymane",
  "passed": "przeszło",
  "masked": "zamaskowano",
  "stopped": "zatrzymano",
  "not reached": "nie doszło",
  "not needed": "nie dotyczy",
  "calls the tool": "woła narzędzie",
  "asks the model": "pyta model",
  "calls the MCP server": "woła serwer MCP",
  "registers the model": "rejestruje model",
  "sends": "wysyła",
  "harmless calculation": "nieszkodliwe obliczenia",
  "code tries to phone home": "kod próbuje połączyć się z atakującym",
  "code tries to run forever": "kod próbuje działać w nieskończoność",
  "Each agent had to reserve {r} tokens before calling the model: {p} for its prompt plus {m} for the longest answer it may get.": "Każdy agent musiał zarezerwować {r} tokenów przed wywołaniem modelu: {p} na prompt i {m} na najdłuższą odpowiedź, jaką może dostać.",
  "{fit} × {r} fits in a pool of {pool}; one more would not. So exactly {fit} agents ran and {stopped} got 429 without calling the model.": "{fit} × {r} mieści się w puli {pool}, a jeden więcej już nie. Dlatego ruszyło dokładnie {fit} agentów, a {stopped} dostało 429 bez wywołania modelu.",
  "The test model answers in a few words, so the {fit} calls really used {spent} tokens. The unused part of each reservation went back to the pool.": "Model testowy odpowiada kilkoma słowami, więc {fit} wywołań zużyło naprawdę {spent} tokenów. Niewykorzystana część każdej rezerwacji wróciła do puli.",
  "1. Pick an example, load a document, or write your own": "1. Wybierz przykład, wgraj dokument albo wpisz własny tekst",
  "Each agent reserves its prompt (about 2 tokens) plus max_tokens. With these numbers exactly {fit} of {n} agents fit in the pool. The rest must be stopped before calling the model, and the pool must never go below zero.": "Każdy agent rezerwuje prompt (ok. 2 tokeny) plus max_tokens. Przy tych liczbach w puli zmieści się dokładnie {fit} z {n} agentów. Reszta musi zostać zatrzymana przed wywołaniem modelu, a pula nie może spaść poniżej zera.",
  "The recipient IS allowed, but the task has read confidential data and outside mail is cleared for public only. If the contract has not been read yet, it is read first.": "Odbiorca JEST dozwolony, ale zadanie przeczytało poufne dane, a poczta na zewnątrz jest dopuszczona tylko do danych publicznych. Jeśli umowa nie była jeszcze przeczytana, zostanie najpierw przeczytana.",
  "in the sandbox": "w piaskownicy",
  "The code tried to reach the network. The sandbox has no network, so the connection failed inside the container. Nothing left the machine; the error below is the code's own, as expected.": "Kod próbował połączyć się z siecią. Piaskownica nie ma sieci, więc połączenie nie udało się wewnątrz kontenera. Nic nie wyszło z maszyny; błąd poniżej to błąd samego kodu i tak ma być.",
  "The code ran past the time limit and the sandbox killed it. The server was never affected.": "Kod przekroczył limit czasu i piaskownica go ubiła. Serwer nie został naruszony.",
  "The code ran out of the memory limit and the sandbox killed it.": "Kod przekroczył limit pamięci i piaskownica go ubiła.",
  "The code failed inside the sandbox. The server was never affected.": "Kod zakończył się błędem wewnątrz piaskownicy. Serwer nie został naruszony.",
  "The code ran in a throw-away container and finished normally.": "Kod wykonał się w jednorazowym kontenerze i zakończył normalnie.",
  "sandbox": "piaskownica",
  "Contained": "Odizolowane",
  "File too large (max 500 KB)": "Plik za duży (maks. 500 KB)",
  "Check a whole document": "Sprawdź cały dokument",
  "Drop a .txt or .md file here (a contract, an e-mail), or pick one. It is checked as a document the agent reads.": "Upuść tu plik .txt albo .md (umowę, e-mail) albo go wybierz. Zostanie sprawdzony jak dokument, który czyta agent.",
  "Choose a file": "Wybierz plik",
  "Sample contracts": "Przykładowe umowy",
  "Load": "Wczytaj",
  "download": "pobierz",
  "Loaded: {name}": "Wczytano: {name}",
  "Clean contract": "umowa czysta",
  "Contract with planted defects": "umowa z ukrytymi defektami",
  "{fit} × {r} fits in a pool of {pool}; one more would not. So at most {fit} agents can hold a reservation at the same moment; the others get 429 without calling the model ({stopped} this time).": "{fit} × {r} mieści się w puli {pool}, a jeden więcej już nie. Dlatego naraz rezerwację może mieć najwyżej {fit} agentów; pozostali dostają 429 bez wywołania modelu (tym razem {stopped}).",
  "{extra} late agent(s) still got in: an agent that finished early had already handed back its unused tokens. The pool was never overdrawn.": "Spóźnionych agentów, którzy i tak weszli: {extra}. Agent, który skończył wcześniej, oddał już niewykorzystane tokeny. Pula ani razu nie została przekroczona.",
  "Each agent reserves its prompt (about 2 tokens) plus max_tokens. With these numbers {fit} of {n} agents fit in the pool at once. The rest must be stopped before calling the model, and the pool must never go below zero.": "Każdy agent rezerwuje prompt (ok. 2 tokeny) plus max_tokens. Przy tych liczbach w puli mieści się naraz {fit} z {n} agentów. Reszta musi zostać zatrzymana przed wywołaniem modelu, a pula nie może spaść poniżej zera.",
};
