// Polish translations. Keys are the English source strings used in App.jsx.
export default {
  // navigation and shell
  "Watch": "Podgląd",
  "Configure": "Konfiguracja",
  "Prove": "Dowody",
  "Live": "Na żywo",
  "Tasks": "Zadania",
  "Audit log": "Dziennik audytu",
  "Controls": "Kontrole",
  "Policy file": "Plik polityki",
  "Attack signatures": "Sygnatury ataków",
  "Tools": "Narzędzia",
  "Run a scenario": "Scenariusze",
  "Test an input": "Sprawdź treść",
  "Budget": "Budżet",
  "Sections": "Sekcje",
  "Language": "Język",
  "Admin key": "Klucz administratora",
  "Current security posture": "Bieżący stan zabezpieczeń",
  "Gateway healthy": "Bramka działa",
  "Gateway degraded": "Bramka ma problem",
  "Connecting": "Łączenie",
  "Policy": "Polityka",
  "Profile": "Profil",
  "AI review on {model}": "Ocena AI: {model}",
  "Test mode: prompts go to OpenRouter (cloud)": "Tryb testowy: prompty idą do OpenRouter (chmura)",
  "AI review on the local scorer": "Ocena AI przez lokalny klasyfikator",
  "{n} attack signatures": "Sygnatur ataków: {n}",
  "AI review forced to “safe” (demo)": "Ocena AI wymuszona na „bezpieczne” (demo)",
  "Off: {list}": "Wyłączone: {list}",

  // decisions
  "Allowed": "Dozwolone",
  "Redacted": "Zredagowane",
  "Blocked": "Zablokowane",
  "allowed": "dozwolonych",
  "redacted": "zredagowanych",
  "blocked": "zablokowanych",
  "Redact": "Redaguj",
  "Block": "Blokuj",

  // live
  "Connecting to the gateway…": "Łączenie z bramką…",
  "No agent traffic yet. Run a scenario to see decisions here.": "Agenci jeszcze nic nie robili. Uruchom scenariusz, a decyzje pojawią się tutaj.",
  "decisions so far:": "decyzji do tej pory:",
  "Decisions as they happen": "Decyzje na bieżąco",
  "Streaming": "Na żywo",
  "tool ran": "narzędzie wykonane",
  "never reached the tool": "nie dotarło do narzędzia",
  "Waiting for the next request. Open “Run a scenario” in another tab and watch it arrive.": "Czekam na kolejne żądanie. Otwórz „Scenariusze” w innej karcie i obserwuj, jak spływają decyzje.",
  "What actually reached the tools": "Co naprawdę dotarło do narzędzi",
  "e-mails delivered by the mail server": "e-maili wysłanych przez serwer pocztowy",
  "External HTTP posts": "Wysyłki HTTP na zewnątrz",
  "Memos saved": "Zapisane notatki",
  "{n} calls": "wywołań: {n}",
  "Counted inside the tool service itself. A blocked request never increments these.": "Liczone wewnątrz usługi narzędzi. Zablokowane żądanie nigdy nie zwiększa tych liczników.",
  "The tool service is not responding.": "Usługa narzędzi nie odpowiada.",
  "Spend": "Wydatki",
  "Tokens spent": "Zużyte tokeny",
  "Held in reservations": "Zarezerwowane",
  "Estimated cost": "Szacowany koszt",
  "Active tasks": "Aktywne zadania",
  "Time added by checks": "Czas dodany przez kontrole",
  "milliseconds": "milisekundy",
  "Stage": "Etap",
  "median": "mediana",
  "Whole decision": "Cała decyzja",
  "Rules doing the most work": "Najczęściej działające reguły",
  "{used} of {limit} tokens used": "Zużyto {used} z {limit} tokenów",
  "{time}: {a} allowed, {r} redacted, {b} blocked": "{time}: dozwolone {a}, zredagowane {r}, zablokowane {b}",
  "Decisions per minute, last hour": "Decyzje na minutę, ostatnia godzina",

  // scenarios
  "Each scenario drives a scripted agent through the real gateway, database and tool service. Nothing is mocked except the agent's choices.": "Każdy scenariusz prowadzi zaprogramowanego agenta przez prawdziwą bramkę, bazę danych i usługę narzędzi. Symulowane są tylko decyzje samego agenta.",
  "Run": "Uruchom",
  "Running…": "Trwa…",
  "{name}: finished": "{name}: zakończono",
  "A normal day": "Zwykły dzień pracy",
  "The agent searches case law, reads the client's contract, asks the local model for risks and files a memo.": "Agent przeszukuje orzecznictwo, czyta umowę klienta, pyta lokalny model o ryzyka i zapisuje notatkę.",
  "Poisoned contract": "Zatruta umowa",
  "The contract hides an instruction to e-mail it to an outside address. The agent tries.": "W umowie ukryto polecenie wysłania jej na obcy adres. Agent próbuje to zrobić.",
  "The AI detector misses": "Detektor AI przeocza atak",
  "The semantic detector is forced to say “safe” and the recipient is one the mandate allows. Only data lineage is left to stop it.": "Detektor semantyczny ma wymuszone „bezpieczne”, a odbiorca jest dozwolony w mandacie. Zatrzymać wyciek może już tylko śledzenie pochodzenia danych.",
  "Wrong client's files": "Dokumenty innego klienta",
  "An agent working for client A reaches for client B's NDA, then tries a path trick.": "Agent pracujący dla klienta A sięga po NDA klienta B, a potem próbuje sztuczki ze ścieżką.",
  "Reused credentials": "Ponowne użycie przepustki",
  "The task ends, the agent keeps its lease and tries to use it again.": "Zadanie się kończy, agent zachowuje przepustkę i próbuje jej użyć ponownie.",
  "Tool changes after approval": "Narzędzie zmienione po zatwierdzeniu",
  "The MCP server silently rewrites a tool description to include an exfiltration instruction.": "Serwer MCP po cichu zmienia opis narzędzia i dopisuje polecenie wyniesienia danych.",
  "Model supply chain": "Łańcuch dostaw modeli",
  "Four models are registered: one clean, one with a pickle that imports os, one hit by CVE-2024-34359, one from a typosquatted host.": "Rejestrujemy cztery modele: czysty, z plikiem pickle importującym os, podatny na CVE-2024-34359 i pobrany z podrobionej domeny.",
  "Thirty agents, one budget": "Trzydziestu agentów, jeden budżet",
  "Thirty agents race for a 10,000-token pool at 1,000 tokens each.": "Trzydziestu agentów walczy o pulę 10 000 tokenów, po 1000 tokenów każdy.",
  "Decisions recorded by the gateway, in order": "Decyzje zapisane przez bramkę, w kolejności",
  "e-mails left the building.": "e-maili opuściło firmę.",
  "e-mail(s) reached the mail server.": "e-mail(e) dotarły do serwera pocztowego.",
  "tokens over budget.": "tokenów ponad budżet.",
  "{ran} agents ran, {stopped} were stopped before calling the model.": "Wykonało się {ran} agentów, {stopped} zatrzymano przed wywołaniem modelu.",
  "Rejected: {why}.": "Odrzucono: {why}.",
  "The tool ran.": "Narzędzie zostało wykonane.",
  "The tool was never called.": "Narzędzie nie zostało wywołane.",
  "Visible tools: {list}.": "Widoczne narzędzia: {list}.",
  "Also flagged: {list}.": "Oznaczono też: {list}.",
  "Rules that fired:": "Zadziałały reguły:",
  "The document was read, but its content was held back from the agent.": "Dokument odczytano, ale jego treść zatrzymano przed agentem.",
  "The document was read and handed over with the dangerous part removed.": "Dokument odczytano i przekazano bez niebezpiecznego fragmentu.",

  // scenario steps (from the backend)
  "search case law": "wyszukanie orzecznictwa",
  "read contract": "odczyt umowy",
  "summarise with local model": "streszczenie przez lokalny model",
  "save internal memo": "zapis notatki wewnętrznej",
  "read poisoned contract": "odczyt zatrutej umowy",
  "compromised agent tries to exfiltrate": "przejęty agent próbuje wynieść dane",
  "legit memo still works": "zwykła notatka nadal działa",
  "read poisoned contract (detector says SAFE)": "odczyt zatrutej umowy (detektor mówi „bezpieczne”)",
  "send contract to an ALLOWED external recipient": "wysyłka umowy do DOZWOLONEGO odbiorcy zewnętrznego",
  "read client B NDA": "odczyt NDA klienta B",
  "path traversal attempt": "próba obejścia ścieżką",
  "during task": "w trakcie zadania",
  "reuse lease after completion": "użycie przepustki po zakończeniu zadania",
  "tools/list (approved)": "tools/list (zatwierdzone)",
  "tools/list (after silent change)": "tools/list (po cichej zmianie)",
  "tools/call quarantined tool": "tools/call narzędzia w kwarantannie",
  "server reverted + admin re-approved": "serwer przywrócony i ponownie zatwierdzony",
  "safe model": "bezpieczny model",
  "pickle importing os.*": "pickle importujący os.*",
  "typosquat source": "podrobiona domena",

  // playground
  "Text to check": "Treść do sprawdzenia",
  "Where it comes from": "Skąd pochodzi",
  "Where it is going": "Dokąd trafia",
  "Most sensitive data the task has read": "Najbardziej poufne dane, które zadanie już przeczytało",
  "Check this input": "Sprawdź",
  "A dry run: the gateway decides, but no model or tool is called.": "Próba na sucho: bramka podejmuje decyzję, ale nie wywołuje modelu ani narzędzia.",
  "Checked. Nothing was executed.": "Sprawdzono. Nic nie zostało wykonane.",
  "A document or tool result the agent reads": "Dokument lub wynik narzędzia czytany przez agenta",
  "A message from the user": "Wiadomość od użytkownika",
  "Arguments the agent sends to a tool": "Argumenty wysyłane przez agenta do narzędzia",
  "The model's answer": "Odpowiedź modelu",
  "Nowhere, just inspect it": "Nigdzie, tylko sprawdź",
  "E-mail outside the firm": "E-mail poza firmę",
  "E-mail inside the firm": "E-mail wewnątrz firmy",
  "Post to an external URL": "Wysyłka na zewnętrzny adres URL",
  "Internal case notes": "Wewnętrzne notatki sprawy",
  "Case-law search query": "Zapytanie do bazy orzecznictwa",
  "Local model prompt": "Prompt do lokalnego modelu",
  "Nothing to stop": "Nie ma czego zatrzymywać",
  "decided in {ms} ms": "zdecydowała w {ms} ms",
  "What the agent would receive": "Co otrzymałby agent",
  "Write or paste anything, then check it. Try a PESEL number, a hidden instruction, or confidential data heading to an outside address.": "Wpisz lub wklej dowolną treść i sprawdź ją. Spróbuj numeru PESEL, ukrytego polecenia albo poufnych danych wysyłanych na zewnątrz.",
  "found {list}": "wykryto: {list}",
  "matched {list}": "dopasowano: {list}",
  "risk {risk} from {backend}": "ryzyko {risk} według: {backend}",
  "{level} data cannot go to {sink} (cleared for {clearance})": "dane {level} nie mogą trafić do {sink} (dopuszczone: {clearance})",

  // controls
  "Loading controls…": "Wczytywanie kontroli…",
  "Strictness": "Poziom rygoru",
  "Sets the defaults for every control below. A setting changed on a single control overrides it.": "Ustawia wartości domyślne dla wszystkich kontroli poniżej. Zmiana ustawienia pojedynczej kontroli ma pierwszeństwo.",
  "Switched to {p}": "Przełączono na: {p}",
  "{what}. Policy is now {v}.": "{what}. Aktualna polityka: {v}.",
  "on": "włączone",
  "off": "wyłączone",
  "Off. Requests are not checked for this.": "Wyłączone. Żądania nie są pod tym kątem sprawdzane.",
  "Task mandates": "Mandaty zadań",
  "Each task may only use its own tools, files and recipients, until it ends.": "Każde zadanie może używać tylko własnych narzędzi, plików i odbiorców, i tylko do swojego zakończenia.",
  "Data lineage": "Pochodzenie danych",
  "Once a task reads confidential data, it cannot send anything to a less trusted place.": "Gdy zadanie przeczyta poufne dane, nie może już niczego wysłać w mniej zaufane miejsce.",
  "Approved models only": "Tylko zatwierdzone modele",
  "Requests to models outside the list are refused.": "Żądania do modeli spoza listy są odrzucane.",
  "Personal data": "Dane osobowe",
  "PESEL, card numbers, IBANs, e-mail addresses and phone numbers.": "PESEL, numery kart, IBAN, adresy e-mail i numery telefonów.",
  "Credentials and keys": "Hasła i klucze",
  "Cloud keys, private keys, tokens and passwords in transit.": "Klucze chmurowe, klucze prywatne, tokeny i hasła w przesyłanych danych.",
  "Known attacks": "Znane ataki",
  "Signatures from the attack feed: unsafe deserialization, code execution, poisoned tools.": "Sygnatury z feedu ataków: niebezpieczna deserializacja, wykonanie kodu, zatrute narzędzia.",
  "Instruction hijacking": "Przejmowanie poleceń",
  "Phrases and hidden markup that try to override the agent's instructions.": "Zwroty i ukryte znaczniki, które próbują nadpisać polecenia agenta.",
  "AI review": "Ocena AI",
  "A local model scores untrusted text for manipulation. It can tighten a decision, never loosen one.": "Lokalny model ocenia niezaufaną treść pod kątem manipulacji. Może zaostrzyć decyzję, nigdy jej nie złagodzi.",
  "Block when risk is at least": "Blokuj, gdy ryzyko wynosi co najmniej",
  "Flag when risk is at least": "Oznaczaj, gdy ryzyko wynosi co najmniej",
  "Thresholds saved": "Zapisano progi",
  "Lower is stricter. Running on {engine}; if it fails, requests are {fallback}.": "Niższy próg oznacza większy rygor. Działa na: {engine}. Przy awarii żądania są {fallback}.",
  "the local scorer": "lokalny klasyfikator",
  "the main model server, or the local scorer if none is configured": "główny serwer modeli, a bez niego lokalny klasyfikator",
  "Use the profile's thresholds": "Użyj progów z profilu",
  "Thresholds follow the profile again": "Progi znów wynikają z profilu",

  // policy
  "active version": "aktywna wersja",
  "Validate": "Sprawdź poprawność",
  "Save as new version": "Zapisz jako nową wersję",
  "Saved as {v}": "Zapisano jako {v}",
  "Valid. Saving will activate it immediately.": "Poprawny. Zapis od razu go aktywuje.",
  "This file is the only source of rules. Saving here or editing it on disk has the same effect within a second. A broken file is rejected and the previous version stays in force.": "Ten plik to jedyne źródło reguł. Zapis tutaj i edycja pliku na dysku działają tak samo, w ciągu sekundy. Błędny plik jest odrzucany, a poprzednia wersja pozostaje w mocy.",
  "History": "Historia",
  "Rejected": "Odrzucona",
  "Restored from v{n}": "Przywrócona z v{n}",
  "Changed via {src}": "Zmiana: {src}",
  "console": "konsola",
  "file": "plik",
  "startup": "start systemu",
  "Restore": "Przywróć",
  "Restored v{n} as {v}": "Przywrócono v{n} jako {v}",
  "in force": "obowiązuje",

  // signatures
  "Loading the attack feed…": "Wczytywanie feedu ataków…",
  "{n} signatures": "Sygnatury: {n}",
  "feed": "feed",
  "from": "z",
  "{id} enabled": "{id} włączona",
  "{id} disabled": "{id} wyłączona",
  "{id} removed": "Usunięto {id}",
  "{id} added. It applies to the next request.": "Dodano {id}. Działa od następnego żądania.",
  "Remove": "Usuń",
  "Add a pattern": "Dodaj wzorzec",
  "Signature ID": "Identyfikator sygnatury",
  "What it catches": "Co wykrywa",
  "e.g. Requests to wire funds": "np. prośby o przelew środków",
  "Regular expression, case-insensitive": "Wyrażenie regularne, bez rozróżniania wielkości liter",
  "Severity": "Waga",
  "Sample text to try it on": "Przykładowy tekst do sprawdzenia",
  "Try it": "Wypróbuj",
  "Add to feed": "Dodaj do feedu",
  "Matches: {list}": "Dopasowania: {list}",
  "No match in the sample.": "Brak dopasowań w przykładzie.",
  "low": "niska",
  "medium": "średnia",
  "high": "wysoka",
  "critical": "krytyczna",

  // tasks
  "Tasks and their mandates": "Zadania i ich mandaty",
  "Task": "Zadanie",
  "For": "Dla kogo",
  "Data seen": "Przeczytane dane",
  "Status": "Status",
  "Calls": "Wywołania",
  "delegated by {id}": "zlecone przez {id}",
  "agent": "agent",
  "{a} of {b}": "{a} z {b}",
  "No tasks yet. Run a scenario or create one through the API.": "Nie ma jeszcze zadań. Uruchom scenariusz albo utwórz zadanie przez API.",
  "Revoke mandate": "Odbierz mandat",
  "Mandate revoked. Its lease no longer works.": "Mandat odebrany. Przepustka przestała działać.",
  "Most sensitive data read": "Najbardziej poufne przeczytane dane",
  "May read": "Może czytać",
  "May use": "Może używać",
  "May write to": "Może pisać do",
  "nothing": "niczego",
  "no e-mail recipients": "brak odbiorców e-mail",
  "Tokens": "Tokeny",
  "{a} spent of {b}": "zużyto {a} z {b}",
  "Expires": "Wygasa",
  "What happened": "Przebieg",
  "by": "reguła",
  "Read {label} data; the task is now {now}.": "Przeczytano dane: {label}. Zadanie ma teraz poziom: {now}.",
  "Tool ran": "Narzędzie wykonane",
  "Tool not called": "Narzędzie niewywołane",
  "Select a task to see its mandate and every decision made for it.": "Wybierz zadanie, aby zobaczyć jego mandat i wszystkie podjęte decyzje.",
  "active": "aktywne",
  "completed": "zakończone",
  "revoked": "odebrane",
  "contract review": "analiza umowy",
  "research": "research",
  "simulation": "symulacja",

  // tools
  "Tool definitions are pinned when first seen. If a server changes one later, the tool is hidden from agents and refused until someone approves the new text.": "Definicje narzędzi są zapamiętywane przy pierwszym użyciu. Jeśli serwer później którąś zmieni, narzędzie znika dla agentów i jest blokowane, dopóki ktoś nie zatwierdzi nowego opisu.",
  "Approved": "Zatwierdzone",
  "Quarantined": "W kwarantannie",
  "pinned": "odcisk",
  "Quarantine": "Kwarantanna",
  "Approve current text": "Zatwierdź obecny opis",
  "{id} quarantined": "{id} w kwarantannie",
  "{id} approved with its current definition": "{id} zatwierdzone z obecną definicją",
  "Changed to": "Zmieniono na",
  "Simulate a silent change on the server": "Zasymuluj cichą zmianę na serwerze",
  "The tool server changed a description. Watch it get quarantined.": "Serwer narzędzi zmienił opis. Zobacz, jak trafia do kwarantanny.",
  "Restore the server": "Przywróć serwer",
  "Tool server restored to its original definitions": "Przywrócono pierwotne definicje narzędzi",

  // budget
  "Race for one budget": "Wyścig o jeden budżet",
  "Agents start at the same moment and share a single pool. Each request reserves its maximum cost before the model is called.": "Agenci startują w tej samej chwili i dzielą jedną pulę. Każde żądanie rezerwuje swój maksymalny koszt, zanim zostanie wywołany model.",
  "Agents": "Agenci",
  "Pool, tokens": "Pula tokenów",
  "Per request": "Na żądanie",
  "Racing…": "Trwa wyścig…",
  "Start {n} agents": "Uruchom agentów: {n}",
  "Race finished": "Wyścig zakończony",
  "Uses the mock model and a throwaway user, so it does not touch real budgets or latency figures.": "Używa modelu testowego i jednorazowego użytkownika, więc nie wpływa na prawdziwe budżety ani pomiary czasu.",
  "Agents that ran": "Agenci, którzy się wykonali",
  "Stopped before the model call": "Zatrzymani przed wywołaniem modelu",
  "Committed": "Zaangażowane",
  "{a} of {b} tokens": "{a} z {b} tokenów",
  "Start a race to see how many agents get through and whether the pool ever goes negative.": "Uruchom wyścig, aby zobaczyć, ilu agentów przejdzie i czy pula kiedykolwiek spadnie poniżej zera.",
  "Budgets": "Budżety",
  "Scope": "Zakres",
  "Used": "Zużycie",
  "Spent": "Zużyte",
  "Held": "Zarezerwowane",
  "Limit": "Limit",
  "Waiting for reconciliation": "Czekające na rozliczenie",
  "The provider did not confirm these calls, so their tokens stay reserved.": "Dostawca nie potwierdził tych wywołań, więc ich tokeny pozostają zarezerwowane.",
  "{n} tokens for": "{n} tokenów dla",
  "Release": "Zwolnij",
  "Reservation released": "Rezerwacja zwolniona",

  // audit
  "Decision": "Decyzja",
  "Any": "Dowolna",
  "Rule": "Reguła",
  "Event": "Zdarzenie",
  "Download JSONL": "Pobierz JSONL",
  "Download CSV": "Pobierz CSV",
  "Entries can only be added. The database rejects edits and deletions, and evidence never contains the raw text that was checked.": "Wpisy można tylko dodawać. Baza danych odrzuca edycję i usuwanie, a dowody nigdy nie zawierają sprawdzanej treści.",
  "Time": "Czas",
  "Where": "Gdzie",

  // classification levels and profiles
  "public": "publiczne",
  "internal": "wewnętrzne",
  "confidential": "poufne",
  "secret": "tajne",
  "strict": "rygorystyczny",
  "balanced": "zrównoważony",
  "permissive": "liberalny",
  "blocked (on failure)": "blokowane",
  "allowed (on failure)": "przepuszczane",

  // channels, backends, stages, match types
  "model": "model",
  "tool": "narzędzie",
  "mcp": "MCP",
  "playground": "test",
  "model_register": "rejestracja modelu",
  "heuristic": "lokalny klasyfikator",
  "main": "główny serwer modeli",
  "override": "wymuszenie (demo)",
  "mandate": "mandat",
  "deterministic": "deterministyczne",
  "signatures": "sygnatury",
  "data flow": "przepływ danych",
  "semantic": "semantyczne",
  "budget": "budżet",
  "execute": "wykonanie",
  "model call": "wywołanie modelu",
  "output deterministic": "wyjście: deterministyczne",
  "output signatures": "wyjście: sygnatury",
  "result deterministic": "wynik: deterministyczne",
  "result signatures": "wynik: sygnatury",
  "result semantic": "wynik: semantyczne",
  "regex": "wyrażenie regularne",
  "pickle scan": "skan pickle",
  "component": "komponent",
  "gguf template": "szablon GGUF",
  "model source": "źródło modelu",
  "tool hash mismatch": "zmiana odcisku narzędzia",

  // reason codes and event kinds (humanised: lower case, spaces)
  "pii detected": "wykryto dane osobowe",
  "secret detected": "wykryto sekret",
  "prompt injection heuristic": "próba przejęcia poleceń",
  "known attack signature": "znana sygnatura ataku",
  "data flow violation": "naruszenie przepływu danych",
  "semantic manipulation": "manipulacja wykryta przez AI",
  "semantic suspicious": "treść podejrzana według AI",
  "semantic guard unavailable": "ocena AI niedostępna",
  "semantic ok": "ocena AI bez zastrzeżeń",
  "budget exceeded": "przekroczony budżet",
  "guard budget exceeded": "przekroczony budżet kontroli",
  "tool not in mandate": "narzędzie spoza mandatu",
  "resource not in mandate": "zasób spoza mandatu",
  "recipient not allowed": "niedozwolony odbiorca",
  "model not allowed": "niezatwierdzony model",
  "model not in mandate": "model spoza mandatu",
  "model unavailable": "model niedostępny",
  "tool quarantined": "narzędzie w kwarantannie",
  "tool definition changed": "zmieniona definicja narzędzia",
  "tool unavailable": "narzędzie niedostępne",
  "tool error": "błąd narzędzia",
  "unknown tool": "nieznane narzędzie",
  "memory cross case": "pamięć innej sprawy",
  "capability expired": "przepustka wygasła",
  "capability completed": "zadanie zakończone, przepustka nieważna",
  "capability revoked": "przepustka odebrana",
  "lease invalid": "nieprawidłowa przepustka",
  "lease agent mismatch": "przepustka innego agenta",
  "decision": "decyzja",
  "policy changed": "zmiana polityki",
  "policy rejected": "odrzucona polityka",
  "feed changed": "zmiana feedu",
  "feed rejected": "odrzucony feed",
  "task created": "utworzono zadanie",
  "task completed": "zakończono zadanie",
  "task delegated": "zlecono podzadanie",
  "task revoked": "odebrano mandat",
  "delegation denied": "odmowa delegacji",
  "tool approved": "zatwierdzono narzędzie",
  "tool quarantined ": "kwarantanna narzędzia",
  "simulation run": "symulacja",
  "semantic override": "wymuszenie oceny AI",
  "demo tool poisoned": "demo: zmiana narzędzia",
  "document label changed": "zmiana etykiety dokumentu",
  "reservation reconciled": "rozliczono rezerwację",
  "memory deleted": "usunięto wpis pamięci",
  "ignore instructions": "ignorowanie poleceń",
  "ignore instructions pl": "ignorowanie poleceń (PL)",
  "role override": "zmiana roli",
  "system prompt exfil": "wyciąganie promptu systemowego",
  "hidden ai note": "ukryta notatka dla AI",
  "concealment": "ukrywanie działań",

  // agent console
  "Be the agent": "Bądź agentem",
  "Allowed.": "Dozwolone.",
  "Allowed. The tool ran.": "Dozwolone. Narzędzie zostało wykonane.",
  "Ask the local model": "Zapytaj lokalny model",
  "Ask the model": "Model AI",
  "Client": "Klient",
  "Contract review for a client": "Analiza umowy klienta",
  "Public legal research": "Publiczny research prawny",
  "Do it": "Wykonaj",
  "Done.": "Gotowe.",
  "End the task": "Zakończ zadanie",
  "Most sensitive data read so far": "Najbardziej poufne dane przeczytane do tej pory",
  "New task": "Nowe zadanie",
  "Outside the mandate": "Poza mandatem",
  "Read": "Czytanie",
  "Read client A's contract": "Przeczytaj umowę klienta A",
  "Read client B's NDA": "Przeczytaj NDA klienta B",
  "Read the contract with a hidden instruction": "Przeczytaj umowę z ukrytym poleceniem",
  "Read the public NDA template": "Przeczytaj publiczny wzór NDA",
  "Run code": "Uruchom kod",
  "Save an internal memo": "Zapisz notatkę wewnętrzną",
  "Search and write": "Szukanie i zapis",
  "Search case law": "Szukaj w orzecznictwie",
  "Send an e-mail": "Wyślij e-mail",
  "Send outside": "Wysyłka na zewnątrz",
  "Start a task on the left first.": "Najpierw rozpocznij zadanie po lewej stronie.",
  "Start the task": "Rozpocznij zadanie",
  "The gateway refused the request before looking at it.": "Bramka odrzuciła żądanie, zanim w ogóle je sprawdziła.",
  "The mail server delivered it.": "Serwer pocztowy go wysłał.",
  "The mail server received nothing.": "Serwer pocztowy niczego nie dostał.",
  "The request never reached the tool.": "Żądanie nie dotarło do narzędzia.",
  "The task is over, but you can keep clicking: the old pass no longer opens anything.": "Zadanie się skończyło, ale możesz dalej klikać: stara przepustka niczego już nie otwiera.",
  "The tool ran, but its output was held back from the agent.": "Narzędzie zadziałało, ale jego wynik zatrzymano przed agentem.",
  "The tool ran; the dangerous part was removed before the agent saw it.": "Narzędzie zadziałało, a niebezpieczny fragment usunięto, zanim zobaczył go agent.",
  "You are the AI assistant now. Start a task, then try actions. Each click goes through the real gateway, exactly like an agent's request would, and you see what the guard decided and why.": "Teraz Ty jesteś asystentem AI. Rozpocznij zadanie i próbuj różnych akcji. Każde kliknięcie przechodzi przez prawdziwą bramkę, dokładnie jak żądanie agenta, a Ty widzisz, co postanowił strażnik i dlaczego.",
  "Your pass": "Twoja przepustka",
  "Your task now carries {level} data. From here on, nothing it produces may go anywhere cleared for less.": "Twoje zadanie zawiera teraz dane: {level}. Od tej chwili nic, co wytworzy, nie może trafić tam, gdzie dopuszczono mniej poufne dane.",
  "[content withheld from the agent]": "[treść zatrzymana przed agentem]",
  "not on your pass": "poza Twoją przepustką",
  "{n} external HTTP posts, {m} memos saved. Counted by the tools themselves.": "Wysyłek HTTP na zewnątrz: {n}, zapisanych notatek: {m}. Liczą same narzędzia.",
  "{tool} is not on this task's pass": "{tool} nie ma na przepustce tego zadania",
  "{r} is not an allowed recipient for this task": "{r} nie jest dozwolonym odbiorcą w tym zadaniu",
  "{p} is outside the files this task may read": "{p} jest poza plikami, które to zadanie może czytać",
  "model {m} is not approved": "model {m} nie jest zatwierdzony",
  "the {scope} budget has no room for this ({dim})": "w budżecie {scope} nie ma na to miejsca ({dim})",
  "{tool} is quarantined": "{tool} jest w kwarantannie",
  "tokens": "tokeny",
  "calls": "wywołania",
  "concurrency": "równoległość",
  "The model was given {doc} as context.": "Model dostał {doc} jako kontekst.",
  "Model": "Model",
  "cloud, public data only": "chmura, tylko dane publiczne",
  "our model server": "nasz serwer modeli",
  "test model, no AI": "model testowy, bez AI",
  "on this machine": "na tym komputerze",
  "not configured": "nieskonfigurowany",
};
